### ISSUE TITLE
[get_rank::WARNING] A None ACGT base found : U

### ISSUE THREAD

**Issue by F0nz0** [hasindu2008/f5c#102]
Hello and thank you for your f5c software!
I launched an f5c eventalign job on a basecalled fastq file after the indexing step. 
The computation are still running but, the stderr is outputting this message and stdout eventalign file is still at 0 bytes:
```
[init_iop] Spawning 9 I/O processes to circumvent HDF hell
[meth_main::11.867*0.49] 512 Entries (1.1M bases) loaded
[get_rank::WARNING] A None ACGT base found : U
[get_rank::WARNING] A None ACGT base found : U
[get_rank::WARNING] A None ACGT base found : U
[get_rank::WARNING] A None ACGT base found : U
[get_rank::WARNING] A None ACGT base found : U
[get_rank::WARNING] A None ACGT base found : U
[get_rank::WARNING] A None ACGT base found : U
[get_rank::WARNING] A None ACGT base found : U
...
..
.
```

Obviously, the fastq has been generated basecalling fast5 files obtained via ONT direct-RNA sequencing protocol thus the fastq contains U instead of T. Can I ignore this warning? Is there a way to avoid the production of this warning (the stderr file is already huge, I mean 30 GB and it is still growing up...)?

**Comment by hasindu2008** [comment]
If it is rna data, f5c requires the --rna flag. Did you specify it?

**Comment by F0nz0** [comment]
No I forgot to set this flag. Thank you very much for your clarification.
