### ISSUE TITLE
call-methylation crashes with stack smashing detected

### ISSUE THREAD

**Issue by TromboneEngineer** [hasindu2008/f5c#104]
I recently got f5c v0.8 installed and configured with CUDA. However, trying to run call-methylation results in crashing as follows:

`~/f5c-v0.8/f5c call-methylation -t 8 -r sample.fastq -g sample.fasta -b Sorted-sample.bam > f5c_result.tsv`
[meth_main::INFO] Default methylation tsv output format is changed from f5c v0.7 onwards to match latest nanopolish output. Set --meth-out-version=1 to fall back to the old format.
[init_cuda] Running on NVIDIA GeForce GTX 1060 6GB (device id 0)
[cuda_freemem] 5.36 GB free of total 5.93 GB GPU memory
[init_cuda] Max GPU capacity 3.2M bases
[init_cuda::INFO] Your GPU can accommodate upto 3.2M bases. You may increase -B option (currently 2.0M) for better performance!
*** stack smashing detected ***: terminated
Aborted (core dumped)

Increasing -B does not change the error:

`~/f5c-v0.8/f5c call-methylation -t 8 -r sample.fastq -g sample.fasta -b Sorted-sample.bam -B 3.2M -o f5c_result.tsv`
[meth_main::INFO] Default methylation tsv output format is changed from f5c v0.7 onwards to match latest nanopolish output. Set --meth-out-version=1 to fall back to the old format.
[init_cuda] Running on NVIDIA GeForce GTX 1060 6GB (device id 0)
[cuda_freemem] 5.37 GB free of total 5.93 GB GPU memory
[init_cuda] Max GPU capacity 3.2M bases
*** stack smashing detected ***: terminated
Aborted (core dumped)

**Comment by hasindu2008** [comment]
Could you kindly run with increased verbosity with -v 10. Alternatively, if the dataset is possible to be shared, I can have a look

**Comment by TromboneEngineer** [comment]
I won't be able to share our data, but I also haven't tested any other data on my installation. This is the output with -v 10:

[meth_main::INFO] Default methylation tsv output format is changed from f5c v0.7 onwards to match latest nanopolish output. Set --meth-out-version=1 to fall back to the old format.
[init_cuda] Running on NVIDIA GeForce GTX 1060 6GB (device id 0)
[print_size] read_ptr array : 4 KB
[print_size] read_lens : 2 KB
[print_size] n_events : 2 KB
[print_size] event ptr : 4 KB
[print_size] Scalings : 8 KB
[print_size] n_event_align_pairs : 2 KB
[cuda_freemem] 5.34 GB free of total 5.93 GB GPU memory
[print_size] read_capacity : 3.0 MB
[print_size] event_table_capacity : 146.2 MB
[print_size] model_kmer_cache_capacity : 36.6 MB
[print_size] event_align_pairs_capacity : 97.5 MB
[print_size] bands_capacity : 3.6 GB
[print_size] trace_capacity : 913.8 MB
[print_size] band_lower_left_capacity : 73.1 MB
[init_cuda] Max GPU capacity 3.2M bases
*** stack smashing detected ***: terminated
Aborted (core dumped)

**Comment by hasindu2008** [comment]
That verbose output does not reveal any potential causes. Could you please run the scripts/test.sh inside ~/f5c-v0.8/ (assuming you downloaded the binaries or release or from github). For instance:

```
cd ~/f5c-v0.8/
scripts/test.sh
```

That will download a test dataset and run. Make sure you run `scripts/test.sh` from inside the `~/f5c-v0.8/` directory. If the script is not present, you can download it from https://raw.githubusercontent.com/hasindu2008/f5c/master/scripts/test.sh.

This way we can see if the problem is caused by something in data or your machine config. Thanks for reporting this by the way. Looks like an error that I have not properly handled.

**Comment by TromboneEngineer** [comment]
Finally got a chance to return to this, but trying your test script from inside my ~/f5c-v0.8/ directory shows a similar stack smashing detected error:

--2022-02-07 12:19:56--  https://f5c.page.link/f5c_ecoli_2kb_region_test
Resolving f5c.page.link (f5c.page.link)... 172.217.13.238, 2607:f8b0:4004:809::200e
Connecting to f5c.page.link (f5c.page.link)|172.217.13.238|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cloudstor.aarnet.edu.au/plus/s/Z4qDfbM2RZTCvxO/download [following]
--2022-02-07 12:19:56--  https://cloudstor.aarnet.edu.au/plus/s/Z4qDfbM2RZTCvxO/download
Resolving cloudstor.aarnet.edu.au (cloudstor.aarnet.edu.au)... 202.158.207.20
Connecting to cloudstor.aarnet.edu.au (cloudstor.aarnet.edu.au)|202.158.207.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Syntax error in Set-Cookie: 5230042dc1897=2tiv79d4cvj99uc5m1057uljk0; path=/plus;; Secure at position 53.
Syntax error in Set-Cookie: oc_sessionPassphrase=k0xeWf%2FOG3GZk2H%2BOQgMFYPMsY82%2BtJqkdDwEHDyZOcsnTrJxIqwBl8fxP8imMoEb9lw8pVFmKPc8zU0xNkv44Xdca4RdKgPTglY2QUrUf3371vmWkipAKqoK6UxwJ6y; path=/plus;; Secure at position 168.
Length: 18378664 (18M) [application/x-compressed]
Saving to: ‘test/data.tgz’

test/data.tgz       100%[===================>]  17.53M  6.22MB/s    in 2.8s    

2022-02-07 12:20:00 (6.22 MB/s) - ‘test/data.tgz’ saved [18378664/18378664]

Extracting. Please wait.
[parse_index_options::INFO] Consider using --iop option for fast parallel indexing
[readdb] indexing test/ecoli_2kb_region/fast5_files
[readdb] num reads: 112, num reads with path to fast5: 112
[main] Version: 0.8
[main] CMD: ./f5c index -d test/ecoli_2kb_region/fast5_files test/ecoli_2kb_region/reads.fasta
[main] Real time: 0.055 sec; CPU time: 0.070 sec; Peak RAM: 0.009 GB

[init_cuda] Running on NVIDIA GeForce GTX 1060 6GB (device id 0)
[cuda_freemem] 5.43 GB free of total 5.93 GB GPU memory
[init_cuda] Max GPU capacity 3.2M bases
[init_cuda::INFO] Your GPU can accommodate upto 3.2M bases. You may increase -B option (currently 2.0M) for better performance!
*** stack smashing detected ***: terminated
Aborted (core dumped)

**Comment by hasindu2008** [comment]
Oh. So seems like it is something related to the system. Can you give me a bit more details like:
1. are you using the compiled binaries or did you compile them yourself?
2. The operating system (lsb_release -a)
3. CPU (lscpu)
4. RAM (lsmem)
5. GBLIC version (ldd --version)
6. Resolved dynamic libraries (ldd ./f5c)

**Comment by TromboneEngineer** [comment]
I downloaded v0.8 release from Github and compiled f5c with the recommended commands from the build documentation:

>wget https://github.com/hasindu2008/f5c/releases/download/v0.8/f5c-v0.8-release.tar.gz
>tar -xvzf f5c-v0.8-release.tar.gz
>cd f5c-v0.8/
>sudo apt-get install libhdf5-dev zlib1g-dev
>scripts/install-hts.sh
>./configure
>make cuda=1

>lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

(Technically I use Ubuntu Studio for this 20.04 LTS, but there shouldn't be any glaring differences from Ubuntu other than the DE)

>lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Stepping:                        13
CPU MHz:                         4518.267
CPU max MHz:                     4700.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6000.00
Virtualization:                  VT-x
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled v
                                 ia prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
                                  pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RS
                                 B filling
Vulnerability Srbds:             Mitigation; TSX disabled
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                                 r pge mca cmov pat pse36 clflush dts acpi mmx f
                                 xsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rd
                                 tscp lm constant_tsc art arch_perfmon pebs bts 
                                 rep_good nopl xtopology nonstop_tsc cpuid aperf
                                 mperf pni pclmulqdq dtes64 monitor ds_cpl vmx s
                                 mx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid s
                                 se4_1 sse4_2 x2apic movbe popcnt tsc_deadline_t
                                 imer aes xsave avx f16c rdrand lahf_lm abm 3dno
                                 wprefetch cpuid_fault epb invpcid_single ssbd i
                                 brs ibpb stibp ibrs_enhanced tpr_shadow vnmi fl
                                 expriority ept vpid ept_ad fsgsbase tsc_adjust 
                                 bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx
                                  smap clflushopt intel_pt xsaveopt xsavec xgetb
                                 v1 xsaves dtherm ida arat pln pts hwp hwp_notif
                                 y hwp_act_window hwp_epp md_clear flush_l1d arc
                                 h_capabilities

>lsmem
RANGE                                 SIZE  STATE REMOVABLE  BLOCK
0x0000000000000000-0x000000007fffffff   2G online       yes   0-15
0x0000000100000000-0x000000087fffffff  30G online       yes 32-271

Memory block size:       128M
Total online memory:      32G
Total offline memory:      0B

>ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

>ldd ./f5c
	linux-vdso.so.1 (0x00007fffccdc1000)
	libhdf5_serial.so.103 => /lib/x86_64-linux-gnu/libhdf5_serial.so.103 (0x00007f06f1c24000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f06f1c08000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f06f1be5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f06f1bda000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f06f1bd4000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f06f19f2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f06f18a1000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f06f1886000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f06f1694000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f06f21e1000)
	libsz.so.2 => /lib/x86_64-linux-gnu/libsz.so.2 (0x00007f06f168f000)
	libaec.so.0 => /lib/x86_64-linux-gnu/libaec.so.0 (0x00007f06f1686000)

**Comment by hasindu2008** [comment]
Thanks for providing this information so I could narrow down the issue. 

Does this stack smashing issue occur with compiled binaries as well - Could you run the following:

```
VERSION=v0.8
wget "https://github.com/hasindu2008/f5c/releases/download/$VERSION/f5c-$VERSION-binaries.tar.gz" && tar xvf f5c-$VERSION-binaries.tar.gz && cd f5c-$VERSION/
mv ./f5c_x86_64_linux_cuda   f5c
scripts/test.sh
```
This will run the compiled version for CUDA.

Also, could you run:
```
VERSION=v0.8
wget "https://github.com/hasindu2008/f5c/releases/download/$VERSION/f5c-$VERSION-binaries.tar.gz" && tar xvf f5c-$VERSION-binaries.tar.gz && cd f5c-$VERSION/
mv ./f5c_x86_64_linux   f5c
scripts/test.sh
```
This will run the compiled version for CPU-only.

The results from those two will help me to narrow down if it is something to do with the CPU side or the GPU side. Thank you very much for helping to find this bug.

**Comment by TromboneEngineer** [comment]
That is strange, I tested the first set of commands you provided (but not the CPU only version), and the test seemed to work. I now get some warnings that seem to spam the terminal, but it is actually running this time (without a stack smashing detected crash). Now I will have to figure out how to interpret the outputs, thanks for your help!

**Comment by hasindu2008** [comment]
So seems like the compiled binaries does not cause the stack smashing.  So something to do with the compilation. Can you please provide me with the GCC/g++ and nvcc versions, so I could try a compilation with those versions?
```
gcc --version
g++ --version
nvcc --version
```

What are the warnings that came on the terminal?

I could explain the field if you need some help interpreting them.

**Comment by TromboneEngineer** [comment]
Oh the warnings were just about --iop and -K for optimization. I still don't know exact numbers to aim for, but I increased -K and specified --iop (because I hadn't changed the default before).

>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

>gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

>g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by hasindu2008** [comment]
Thanks. I am trying to reproduce your system environment inside a docker.
Can I know how you installed CUDA 10.1 on your Ubuntu 20?
Because on NVIDIA CUDA website, Ubuntu 20 is not listed under CUDA 10.1.
![image](https://user-images.githubusercontent.com/12987163/155240921-33c5a61f-87a7-44bd-ba27-fef36289ce51.png)

**Comment by hasindu2008** [comment]
I am closing this issue for now, as I cannot reproduce it. Likely to be something like getting linked to a wrong cuda library version or something. For now please use the compiled binaries which are statically linked.  Feel free to reopen if you have any more questions.
