### ISSUE TITLE
Cannot index files compressed with gzip, please use bgzip

### ISSUE THREAD

**Issue by mantonglaw** [hasindu2008/f5c#105]
Hello!

I use the following commands to run f5c call-methylation:
/share/home/lius/biosoft/f5c/f5c-v0.8/f5c_x86_64_linux_cuda \
call-methylation -b /share3/lius/tredata/DNA/batch2/xxx/map2GRCh38genome/xxx.clean.fq.gz.map2GRCh38genome.sort.bam \
-g /share/home/lius/ref_data/gencode_GRCh38/all_genome/GRCh38.p13.genome.fa.gz \
--iop 5 \
-t 40 \
--disable-cuda=no \
-r /share3/lius/tredata/DNA/batch2/xxx/xxx.clean.fq.gz \
> /share/home/lius/tredata/f5c_5mC/f5c_call5mC_output/xxx_f5c_call5mC.tsv

And there is a error, Cannot index files compressed with gzip, please use bgzip. 
Could you give me some advise to address the problem?

Thanks in advance

**Comment by hasindu2008** [comment]
Hi,

It could be either the GRCh38.p13.genome.fa.gz or /share3/lius/tredata/DNA/batch2/xxx/xxx.clean.fq.gz or both. Can you the following commands to see which one is not bgzip compressed?

```
file /share/home/lius/ref_data/gencode_GRCh38/all_genome/GRCh38.p13.genome.fa.gz
file /share3/lius/tredata/DNA/batch2/xxx/xxx.clean.fq.gz
```

The easiest solution is to uncompress those two files as:
```
gunzip -k  /share/home/lius/ref_data/gencode_GRCh38/all_genome/GRCh38.p13.genome.fa.gz
gunzip  -k /share3/lius/tredata/DNA/batch2/xxx/xxx.clean.fq.gz
```
Then provide run f5c as:
```
... -g /share/home/lius/ref_data/gencode_GRCh38/all_genome/GRCh38.p13.genome.fa -r /share3/lius/tredata/DNA/batch2/xxx/xxx.clean.fq 
```

**Comment by hasindu2008** [comment]
I am closing this issue for now. Please reopen if you are still facing the issue.
