### ISSUE TITLE
[get_rank::WARNING] A None ACGT base found : U

### ISSUE THREAD

**Issue by JeremyQuo** [hasindu2008/f5c#106]
When I use f5c call-methylation, it return this warning
[get_rank::WARNING] A None ACGT base found : U.

Will it influence the results?
Can --rna option  only applied on the evenalign?

**Comment by hasindu2008** [comment]
Unfortunately, f5c/nanopolish does not have a methylation model available for RNA. So methylation calling only works for DNA.
