### ISSUE TITLE
Meth-freq treshold issue

### ISSUE THREAD

**Issue by jotanan98** [hasindu2008/f5c#110]
Hi,
I recently did methyl-calling using f5c, I want to plot the meth-freq tsv file, but i realized that some of the methyl-calling.tsv reads were kept into the meth-freq.tsv file even tho they have log-like-ratio between 2.5 and -2.5. Is this normal? I am asking because some of these reads have 100% meth-freq even tho they don't pass the treshold.

I added some picture, you can look at the region starting at 11296

Thanks
![methyl-calling](https://user-images.githubusercontent.com/93542151/177349531-8c72df78-24f2-46bd-8787-472ca18831b5.png)
![meth-freq](https://user-images.githubusercontent.com/93542151/177349534-e39d18a9-7b3f-4a85-a6df-3e5b519559e9.png)

**Comment by hasindu2008** [comment]
Hi Jonathan,

Is there another read that has methylation in that position particular position (chr1 11296)? Is it possible to send the meth_calling.tsv file so that I could inspect why this is happening?

Also could you do a `grep "11296" methyl_calling.tsv`?

**Comment by hasindu2008** [comment]
If there are any more issues please reopen or start a new issue :) Thanks for trying f5c out.
