### ISSUE TITLE
Error in eventalign

### ISSUE THREAD

**Issue by Tomcxf** [hasindu2008/f5c#113]
Well, I test f5c to index, it really faster than before. It works!
but when I use f5c to eventalign, it print out on screen:
[E::faidx_adjust_position] The sequence "NM_001035539.1" not found
[E::faidx_adjust_position] The sequence "NM_001035539.1" not found
......
[get_rank::WARNING] A None ACGT base found : U
[get_rank::WARNING] A None ACGT base found : U
[get_rank::WARNING] A None ACGT base found : U
......
Now it has run two hours, and there is nothing written in output file
I don't know what's wrong with it. Or it is just normal.
Thank you!

**Comment by hasindu2008** [comment]
Hi

First can I confirm if your date is DNA or RNA? If the data is RNA, make sure you specify --rna option to f5c eventalign. Then that warning on U should disappear. 

On that warning about the contig not found, what are you specifying to -g option? Make sure if that genome you specify to -g is the same as the reference you used to generate the BAM file?

**Comment by hasindu2008** [comment]
@Tomcxf Any updates on this?

**Comment by Tomcxf** [comment]
Sorry to reply so late.
The problem has been solve through your advise 
Thank you!

**Comment by hasindu2008** [comment]
How is the runtime performance like? Was there an improvement?

**Comment by Tomcxf** [comment]
yes, it can improve time greatly!
Thank you for your donation to ONT!
