### ISSUE TITLE
f5c index

### ISSUE THREAD

**Issue by pedramPP** [hasindu2008/f5c#117]
Hi there,

Is it possible to use fastq indexed with f5c for downstream work with nanopolish and vice versa? If yes, does the versions of nanopolish/f5c matters?

Best,
Pedram

**Comment by hasindu2008** [comment]
In which format is your raw data in, fast5 or blow5?

**Comment by pedramPP** [comment]
They sre in fast5

**Comment by hasindu2008** [comment]
The indexes are compatible in-between f5c and nanopolish, irrespective of the version, as far as I remember. Which module in Nanopolish are you going to use?

**Comment by pedramPP** [comment]
eventalign and call_methylation

**Comment by hasindu2008** [comment]
f5c should give same results as nanopolish for those modules is you match the parameters (minimum qscore and if secondary alignments are considered)

**Comment by pedramPP** [comment]
Thanks a lot

**Comment by vahidAK** [comment]
Sorry, just another question on this topic. For other formats such as slow5 or blow5, the fastq index made by one tool can still be used with the other tool?

**Comment by vahidAK** [comment]
Sorry, to expand on this topic. What about Slow5 or blow5? Can fastq index made by one tool be used by the other tool?

**Comment by hasindu2008** [comment]
Yes, with a slight catch.  If you use nanopolish to index (a fastq  with a blow5), it will create a file like `reads.fastq.index.readdb` with following content.

```
*       path/to/reads.blow5
```

To use f5c, simply rename this reads.fastq.index.readdb to something else, sor instance, reads.fastq.index.readdb2. When you want to run nanopolish, rename it back.

If you used nanopolish to index, you can create a .readbb file manually like below and then use f5c.
```
echo -e "*\tpath/to/reads.blow5" >  reads.fastq.index.readdb
```

Do you think it is worth implementing f5c to be producing an intercompatible index to nanopolish? I was planning to but did not really do it as I thoughts instances like this would be infrequent.

**Comment by vahidAK** [comment]
Thanks, @hasindu2008. So, nanopolish indexed fastq using slow5 or blow5 can be used with f5c. But, can f5c indexed fastq using slow5 or blow5 also be used with nanopolish?

I think this might be beneficial as there are some nanopolsih modules not exist in f5c and f5c indexing is really fast compared to nanopolish, so it can be used in combination with nanopolish on slow5 and blow5 files as well.

**Comment by hasindu2008** [comment]
@vahidAK  

I made a mistake in my previous comment when typing through my phone and now edited it.

F5c indexed fastq using slow5 or blow5  can also be used with nanopolish if you can create a .readbb file manually like below.
```
echo -e "*\tpath/to/reads.blow5" >  reads.fastq.index.readdb
```

**Comment by vahidAK** [comment]
Thanks, @hasindu2008
