### ISSUE TITLE
resquiggle in f5c

### ISSUE THREAD

**Issue by loganylchen** [hasindu2008/f5c#118]
Hi there,

I am interested in the resquiggle module, as I am not a c programmer, and it is not easy for me to read the source code. May I ask how you generated the simulation signal of the target sequence which was used to align to?

I appreciate any help you can provide.

**Comment by hasindu2008** [comment]
Hi

See if the information you need is there in our f5c paper https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03697-x or its supplementary material https://hasindu2008.github.io/f5c/nanopore_signal_alignment_supplementary_material.pdf?
