### ISSUE TITLE
Graphmap2 compatibility

### ISSUE THREAD

**Issue by F0nz0** [hasindu2008/f5c#122]
Good morning and thank you very much for your sofware. I really appretiate it. Because of some experimental isuees, I have been obliged to use Graphmap2 instead of Minimap2 aligner.  What I found was the following: when aligning the reads with graphmap2, f5c wasn't able to perform the eventalign procedures while, on the same reads and fastq files, by the change of the only bam file with the one generated via minimap2, no problems have occurred. Is this due to an incompatibility of f5c sofware with graphmap2? In addition, nanopolish was able to perform the eventalign step on both the bam files (from minimap2 and graphmap2). To note, I was working on direct RNA Nanopore sequencing runs. Do you have any suggestion to fix this behaviour?

Many thanks!

**Comment by hasindu2008** [comment]
Hi,

I never checked with graphmap. What is the error f5c is outputting? 

Also, would you mind sending a small example BAM file from the graph map, along with the fastq and reference as well?

**Comment by F0nz0** [comment]
No errors! With BAM files generated by minimap2, f5c was able to perform the eventalign very well...with the graphmap2 ones, 0.0M bases were read and the script generated an empty eventalign output except for the header row.
The indexing goes well, I think the problem is with the graphmap2 BAM file. 
This is the stderr flow:
`[init_iop] Spawning 10 I/O processes to circumvent HDF hell
[init_core::INFO][1;34m builtin RNA nucleotide model loaded[0m
[meth_main::0.048*1.11] 0 Entries (0.0M bases) loaded
[pthread_processor::0.049*1.12] 0 Entries (0.0M bases) processed
[meth_main] total entries: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0
[meth_main] total bases: 0.0 Mbases
[meth_main] Data loading time: 0.035 sec
[meth_main]     - bam load time: 0.034 sec
[meth_main]     - fasta load time: 0.000 sec
[meth_main]     - fast5 load time: 0.001 sec
[meth_main]         - fast5 open time: 0.001 sec
[meth_main]         - fast5 read time: 0.000 sec
[meth_main] Data processing time: 0.000 sec
[meth_main] Data output time: 0.000 sec
[meth_main::INFO][1;34m Performance bounded by file I/O. File I/O took 0.035 sec than processing[0m
[main] Version: 0.7
[main] CMD: f5c eventalign --iop 10 -t 15 -r subset_unmod.fastq -b subset_unmod_cc1_gmap.bam -g refs.fa --rna --scale-events --print-read-names --samples --signal-index
[main] Real time: 0.051 sec; CPU time: 0.056 sec; Peak RAM: 0.005 GB`

No probem using the same reference and fastq but with a minimap2 BAM files.

Here some rows of the graphmap2 BAM file:

`$ samtools view -h subset_mod_gmap.bam | head
@HD     VN:1.0  SO:coordinate
@SQ     SN:gBlock1      LN:999
@SQ     SN:gBlock2      LN:999
@SQ     SN:gBlock3      LN:999
@PG     ID:graphmap     PN:graphmap     CL:/home/adri/graphmap2/bin/Linux-x64/graphmap2 -x rnaseq -t 2 -r /mnt/c/Users/adria/Desktop/refs/gBlock_refs_GtoA.fa -d /mnt/c/Users/adria/Desktop/subset_dataset/subset_mod.fastq -o /mnt/c/Users/adria/Desktop/subset_dataset/subset_mod_gmap.sam        VN:v0.6.5 compiled on Mar  8 2023 at 11:20:23
@PG     ID:samtools     PN:samtools     PP:graphmap     VN:1.10 CL:samtools view -@ 2 -S -b subset_mod_gmap.sam
@PG     ID:samtools.1   PN:samtools     PP:samtools     VN:1.10 CL:samtools sort -o subset_mod_gmap.bam -
@PG     ID:samtools.2   PN:samtools     PP:samtools.1   VN:1.10 CL:samtools view -h subset_mod_gmap.bam
c7f55911-3893-4841-8ed0-b7ac32e67600    0       gBlock1 1       0       1S59M1I38M2D4M2I7M1I14M2D9M1I18M3D5M1D2M1D2M2D54M1I2M1D12M1I14M2D15M2D1M1D7M3D20M4D6M1D5M1D4M1I20M2D11M1I41M1I20M2D35M1I4M1D20M1D4M1I7M2D1M2D10M1I39M1I2M3I14M1D2M1D51M1D3M1I10M1I22M1D15M3I72M1D9M1I11M3D9M1I14M1I1M1I13M2D4M1D4M1D3M1I1M3D6M2D33M1D5M1D11M1D14M2D2M1D9M1I25M1D9M2D1M1D6M1D18M2D10M117S        *       0       0       GTCAAATCTACACTGATCACCAAGTTTAACATGCCAACTACGCCAAATTCATTAACTCTCTGCTACCATCACAAATTCCACGGGCTCCCCTAACATTCCTCCCGTATATACATTTCAGCTTTAATCTTGTCTTCCCAAAAAACCTATCAGCCATTAAATTTTTAACCTCTACTTAGACTACCAAAAGCAAATATTCAGACTACCCAATATTTACCATCTCATACAACCCTGCCAAATCCATAGCAAATTCTGATTCAACTGTATTTTCCTATCCACAAATAATATCTCGAATCCTTAACATATCAAGATCATATAATGTCCATCCCTTATAACCATTATCCAATCCTTAGAACTCACCCCGTTACTACCCCCGCCACCTTCTGGATTATCTAACGCTTACTTCGATAACCTCACGACTTATCCTTGATCATCTACAGGAATTCATCAGCACTACATTCGCTACCTCCATTAAATTCGTATTATTAAATGCCTTTTACACGCAAACACTCAGTATCAAACATATATTCTATAATTATATAAAACATCATACCTCATAATTACACCATTGTTATATACTTGTTTATTACCCTCACCCACTCATCCCTAACCCAGCTTTACAATTAAATACACTCCCTGTATTTCACGTCCTTACATTATCAAATACCCATCGCATCAACTAAGCCCCTACACCGATCTCCCTTAATACATTTCCTGTAATAACCATTCTACCACTAAATCCTCATCCCGTCCACAAGTTTCAATATCAATCTATTACTTATGACACCATAATTCTCTTGTTATATTGAAAATTAAACACTTCCTACTTGAATTCTTTCTGTCTACCTTATCATTCACTGCTCTCCTACTGTTAATTAGCCTATTTTTTCATATTCCAATAGTACATCTTGGTTCCACATCATCCTGTACCTCCAGACTCTCAAACTATCACTCAGCCTATATTCTAAAAAAATCTCCCTCTCCCATCCAACCATCCCTATCATCACTATTTCCATCTATTCACAACCTGCCTCCATCCCCCTACTCTTATCACCCTACATCTAATAT   ('&04&/-01-.0<2:6)(+4/528675?@,:853+-)05:68648%6657<:;;2(%*$''/633466))/66)4+,-37&*)05&926.&%%%),030:6456%2'1,,%%*./=>1*.79;2%'4,*$%,+.&+,-38=38=?/,&--4432+&&&)&)4(''43+++)'0383.,67'25=B<:;?+9<:24747/)=>:98<:,*$(&-%%%$)++*''-,-4-*$%&)+$*000,?>;>?2.)(/01;93331*'$$'()10(5*&%/04.*((45455&',.615$%&-'$%%++/&&94::96?9977709.750&,0%586,++.-++%%&.13/1657*(7=5'356872-0321.%%0;;1//(%&.*%$%(%599:7/.4676-/00,1--01111/6/'.727*3@?:61'(-1,++-&*,0.0,(00.45)427+*(%&/./-($#&#$(%&)*+326431)$(:50.49:8%,,3+--0254)204733,3-*17576522//.,,,($%&$'(&1217670347./*%&$$$&+7266'''(<3*'10--0*$;:0;;0(2+*%/292;587.+($%3770-''%(,0245392%,$&&'&-+'')'(%(&&-)15/60&*,*&&%%%,/574((*&%,,(#*.(*142420''%%(&(++;9D:488*-,/1..5<3&/40/*/(('$%%'(06/70762+0102,-&$//13+,(/-%+032653>261,)-*-14+(''0352<55*)'&,1/42/+,')25=505%%354+$%$*,%+,%6-4()(<>=8)2///))/861:733834<>7++)0'8,3(873*'')+%&((#$%*))-(44.4',563/8.85-04,$$*.*.,('',),825995:18,,/-%.$+$2151)+*,''+,8::402240)3)48+$%#-*))8;.$$$%+:55232%#&'$+2532.((,%'&&+%$&',/,,*.&#&'&&,*+'$&$$,&%&%%&$%(&&*#&%()&&$*'''%$''$)('&/0//.$$%&#'(),$$%.%$#$#'#&02/&$   MD:Z:13A8A8A8A4T13A19A0A0A8T6^CT15A2C6^TA1C7T11A5^AAA5^C2^C2^AC11A10A10A11C10^C9A10A5^TC3A8A2^AT1^C7^TCC17C2^ATCT6^C1T3^T14A4A4^TA21A10A10A0C7A0A0A10A6^TA1A0A10A9C0A10A3^C6A8A1A0A1^C4T2A3^AT1^CA2A10A10A10A11C14C2^C2^A1C9C9A0C9A10A7^T13A9T11^A0A0C8A21A4T1T3A10A7A0C0T1C9A10^A1T18^CAT1C7A0A0C19A5^AT4^T4^A4^AAC6^AA0A5C0T4T9A10^A0T4^C3C7^T3A10^AA0C1^A6A3A0A0C0C0A0A12A5^A2A0A0A1C2^TT1^C6^C3A8A5^CA10    NM:i:197        AS:i:2976  H0:i:0   ZE:f:0  ZF:f:0  ZQ:i:1065       ZR:i:999
1548d483-29b8-4ecc-bbcb-cfe7c9ef5df7    0       gBlock1 1       0       3S5M1I51M1D12M2I13M1I71M3D18M13S        *       0       0       AGGTCAAATTCTACACTGATCACCAAGTTTAACATGCCAACTACGCCAATTTCGTTAACTTCGCTACCATCACGCGAATTCCACAAAGCTCCCCTATCGTTCCCTTCCCGTATACATTCAGCTTTAATTTGTTCTCTTCCCTGAAACCTATCAGCCATTAAGTTCTTCTAACGCCTCATCTGGAACCAAA  '43=8>8-0(%33644>;;/(#&2/425((-*,787355549165;9>;1,:42,;544-750*)$%,,)&)&&,.04(/'%$2019=40(:39>=551662<78558?6><934451)>8890:7:3)831'%&&%$46.76;223637-)2,4//.%/:8<.)&7$287=2*,$%%$$)-''''($%$      MD:Z:13A8A8A8A8A6^C2A10A21A10A10A2C4C1T0A10A10A5^AAA2A10A4      NM:i:26 AS:i:630        H0:i:0  ZE:f:0      ZF:f:0  ZQ:i:190        ZR:i:999`

**Comment by hasindu2008** [comment]
Hi
Could you try with the option  --min-mapq 0

**Comment by F0nz0** [comment]
Yes! It worked with this parameter. For some strange reasons, graphmap2 gave always either 0 or 255 mapping quality...
Thank you!

**Comment by hasindu2008** [comment]
In the dev branch, I have added a WARNING like below when this situation is detected, which will be up in the next release. Thanks for reporting this scenario.
`[meth_main::WARNING] Skipped 143 reads with MAPQ < 20. Use --min-mapq to change the threshold.`
