### ISSUE TITLE
resquiggle

### ISSUE THREAD

**Issue by caojiabao** [hasindu2008/f5c#123]
hi, I am using resquiggle to match the original signals to the basecalled reads, the whole process is error-free, but only partially matched. Almost 90% of them are not calibrate?

[resquiggle_main] total entries: 5575790, qc fail: 97888, could not calibrate: 4834013, no alignment: 80406, bad read: 0

**Comment by caojiabao** [comment]
> Hi
> 
> What is the command you used? Is it DNA or RNA data? Is it r9 chemistry or r10 chemistry?
f5c_x86_64_linux_cuda resquiggle, DNA, r9.4 chemistry

**Comment by caojiabao** [comment]
I use "f5c_x86_64_linux_cuda resquiggle" to align DNA raw sigals to basecalled reads.  r9 chemistry

**Comment by hasindu2008** [comment]
@caojiabao Could you please provide the whole command line you used with parameters? 
Is this a publicly available dataset so I could try (you could share a small portion if you wish).

**Comment by hasindu2008** [comment]
@caojiabao any updates on this?
