### ISSUE TITLE
f5c index error in snakemake

### ISSUE THREAD

**Issue by Tomcxf** [hasindu2008/f5c#125]
Hi Dr.Gamaarachchi !
Thanks for your wonderful f5c tools!
But recently I met a problem putting f5c to snakemake.
I use 
```
rule slow_index:
    input:
       fastq,
      file.blow5
    output:
      file.slow5.idx
    threads:8
    shell:
        "f5c_x86_64_linux_cuda index --slow5 {input[1]} {input[0]}"

```
for preparation to nanopolish polya.
But I met 
```
MissingOutputException in rule slow_index in file XXX.py, line 147:
Job 10  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
```
At first I believe that it may be the reason that 'nanopolish polya' doesn't offer a place for idx, but when I fix that the error exist.
When I just simply run f5c index in shell, not in snakemake. The command run well.
So how can I solve that?
Thank you！

**Comment by hasindu2008** [comment]
Hi,

I haven't used snakemake, but can it be because of the output file name? Can you make that `file.blow5.idx` instead of `file.slow5.idx`? 

note relevant to the error: Also if you want to make use of threads, you might have to provide -t {threads} or something

**Comment by Tomcxf** [comment]
That error solved!
But next I met another problem recently.
When I continued, it showed
```
error: could not load the index files for input file ./WT-1/analysis/WT-1.fastq
Please run nanopolish index on your reads (see documentation)
```
I use f5c to index the blow5 file, and then use 'nanopolish polya' to estimate polyA length. Will they unsuitable?
By the way , has f5c add polyA length function?
Thank you!

**Comment by hasindu2008** [comment]
f5c indexed fastq using slow5 or blow5 can also be used with nanopolish if you can create a .readbb file manually like below.
echo -e "*\tpath/to/file.blow5" >  ./WT-1/analysis/WT-1.fastq.index.readdb
Make sure to replace `path/to/` with the appropriate path (relative or absolute path) where the file.blow5 resides.

I have not implemented polyA for f5c.

**Comment by Tomcxf** [comment]
Thanks for your help!
It run well 
but I encounter the same error again
[](https://github.com/jts/nanopolish/issues/1025)
the result show all is -1.0
and the last column are all READ_FAILED_LOAD

I used the nanopolish version you supply in that issue. It worked before but now it doesn't work again.
Thank you!

**Comment by hasindu2008** [comment]
Can you attach the readbb file you created?

**Comment by Tomcxf** [comment]
It shows that 
./WT-1/analysis/slow5/file.blow5

**Comment by Tomcxf** [comment]
It seems that different from the issue mentioned.
Will 
```
echo -e "*\tpath/to/file.blow5" > ./WT-1/analysis/WT-1.fastq.index.readdb 
```
have some problem?

**Comment by hasindu2008** [comment]
It should look like this:
```
*       ./WT-1/analysis/slow5/file.blow5
```

Isn't the command you run
```
echo -e "*\t./WT-1/analysis/slow5/file.blow5" > ./WT-1/analysis/WT-1.fastq.index.readdb 
```

Not that it is a tab, not a space between * and the path.

**Comment by hasindu2008** [comment]
Feel free to reopen if you face another issue
