### ISSUE TITLE
genomic coordinate of dRNA eventalign 

### ISSUE THREAD

**Issue by sunsetyerin** [hasindu2008/f5c#132]
Hi @hasindu2008, I was wondering how to get the genomic coordinate of eventalign.txt file 

'contig  position        reference_kmer  read_index      strand  event_index     event_level_mean        event_stdv      event_length    model_kmer      model_m
ENST00000379236   464     TGCAC   0       t       143     114.64  2.895   0.00367 TGCAC   108.56  3.86    1.25    41906   41917
ENST00000379236   465     GCACC   0       t       144     74.81   7.230   0.00500 GCACC   70.72   1.88    1.73    41891   41906
ENST00000379236   465     GCACC   0       t       145     68.18   1.091   0.00333 GCACC   70.72   1.88    -1.07   41881   41891'

For example, how can I get the genomic position of "ENST00000379236(contig) & 464(position) & TGCAC(kmers)"?

**Comment by hasindu2008** [comment]
Hi @sunsetyerin 

Sorry, your question is not clear to me. What do you mean by getting the genomic coordinate? IN the above example ENST00000379236:464 is the genomic coordinate for that particular k-mer. Do you mean getting it from the FASTA file? 

Can you check the explanation of event alignment output  [here](https://hasindu2008.github.io/f5c/docs/output#eventalign-tsv-output) is of any help?

**Comment by sunsetyerin** [comment]
I've read the explanation, but can I get chromosome, strand, start index, and end index info about certain contig?
For example,
<img width="460" alt="image" src="https://user-images.githubusercontent.com/59498491/236532717-dac2f747-78b0-49ec-af58-b06e39aeea1f.png">

**Comment by hasindu2008** [comment]
So you are using the transcriptome I believe? Without exactly knowing what you are using as the reference, I cannot give the exact answer.

Assuming this your reference transcriptome is the `gencode.v40.transcripts.fa` you can locate the genomic coordinates from the file `gencode.v40.annotation.gtf`.gz that you can download from https://www.gencodegenes.org/human/release_40.html. 

What is your reference FASTA file used for mapping and alignment?

**Comment by sunsetyerin** [comment]
I used transcriptome reference file for mapping 
http://ftp.ensembl.org/pub/release-106/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz

I mean, I know that I can find genomic coordinate from gtf file, but wonder the specific genomic position, not just a range of genomic coordinate, for example,

**Comment by hasindu2008** [comment]
Hi @sunsetyerin 
Sorry for misunderstanding your problem. So you want to get the genomic coordinate of each k-mer position reported in eventalign on the transcriptome. Currently, f5c does not have any option or feature to directly facilitate this. 

So my suggestion is to do this as a post analysis step through a custom script (that takes a transcript coordinate and convert the location based on the coordinate range from the GTF) or an existing library like https://rdrr.io/github/jotsetung/ensembldb/man/transcriptToGenome.html.
