### ISSUE TITLE
Error Running Call Methylation

### ISSUE THREAD

**Issue by katiestoker** [hasindu2008/f5c#135]
Hello, 

Indexing seems to have worked well, however I receive the error "[init_core::ERROR] sam_itr_queryi failed. A problem with the BAM index?" when running f5c call-methylation. 

Thanks!
Katie.

**Comment by hasindu2008** [comment]
How was the BAM file and the BAM index created?
Could you please try after reindexing the BAM file, `samtools index file.bam`?

**Comment by katiestoker** [comment]
The BAM file was created using samtools sort .sam > .bam
I then indexed using samtools index .bam 

I reindexed the bam file in this way and am still getting the error.

**Comment by hasindu2008** [comment]
Is this dataset pretty large? Wondering if you can share an example so I can reproduce the error on my side.

ALternatively, could you try executing `scripts/test.sh` under f5c repository directory to see if you encounter the same error for the example dataset?

**Comment by hasindu2008** [comment]
@katiestoker Also could you please copy-paste the exact command you executed so I can have a look?

**Comment by hasindu2008** [comment]
@katiestoker Any updates on this?

**Comment by katiestoker** [comment]
Hello, 

I was actually using test data to check everything was set up before using my own data. I started again from download and the issue seems to be resolved. Hopefully everything works ok on my own data now. 

Thanks for your help!

Best, 

Katie
