### ISSUE TITLE
f5c v1.2 to run the eventalign in R10 data

### ISSUE THREAD

**Issue by shuyi122425** [hasindu2008/f5c#137]
Hi,

I'm currently working on performing the eventalign function for R10 data using f5C v1.2. However, I'm facing an issue after compiling where I can't seem to find the parameters to specify the eventalign model for R10. I would greatly appreciate it if you could assist me by providing the necessary code to run eventalign with R10 data. 

Thank you!

`f5c-v1.2 
f5c eventalign
Usage: f5c eventalign [OPTIONS] -r reads.fa -b alignments.bam -g genome.fa
       f5c eventalign [OPTIONS] -r reads.fa -b alignments.bam -g genome.fa --slow5 signals.blow5

basic options:
   -r FILE                    fastq/fasta read file
   -b FILE                    sorted bam file
   -g FILE                    reference genome
   -w STR                     limit processing to a genomic region specified as chr:start-end or a list of regions in a .bed file
   -t INT                     number of processing threads [8]
   -K INT                     batch size (max number of reads loaded at once) [512]
   -B FLOAT[K/M/G]            max number of bases loaded at once [5.0M]
   -h                         help
   -o FILE                    output to file [stdout]
   -x STR                     parameter profile to be used for better performance (always applied before other options)
                              e.g., laptop, desktop, hpc; see https://f5c.page.link/profiles for the full list
   --iop INT                  number of I/O processes to read fast5 files [1]
   --slow5 FILE               read from a slow5 file
   --min-mapq INT             minimum mapping quality [20]
   --secondary=yes|no         consider secondary mappings or not [no]
   --verbose INT              verbosity level [0]
   --version                  print version

advanced options:
   --skip-ultra FILE          skip ultra long reads and write those entries to the bam file provided as the argument
   --ultra-thresh INT         threshold to skip ultra long reads [100000]
   --skip-unreadable=yes|no   skip any unreadable fast5 or terminate program [yes]
   --kmer-model FILE          custom nucleotide k-mer model file (format similar to test/r9-models/r9.4_450bps.nucleotide.6mer.template.model)
   --summary FILE             summarise the alignment of each read/strand in FILE
   --sam                      write output in SAM format
   --print-read-names         print read names instead of indexes
   --scale-events             scale events to the model, rather than vice-versa
   --samples                  write the raw samples for the event to the tsv output
   --signal-index             write the raw signal start and end index values for the event to the tsv output
   --rna                      the dataset is direct RNA
   --collapse-events          collapse events that stays on the same reference k-mer
   --min-recalib-events INT   minimum number of events to recalbrate (decrease if your reads are very short and could not calibrate) [200]

developer options:
   --print-events=yes|no      prints the event table
   --print-banded-aln=yes|no  prints the event alignment
   --print-scaling=yes|no     prints the estimated scalings
   --print-raw=yes|no         prints the raw signal
   --debug-break INT          break after processing the specified no. of batches
   --profile-cpu=yes|no       process section by section (used for profiling on CPU)
   --write-dump=yes|no        write the fast5 dump to a file or not
   --read-dump=yes|no         read from a fast5 dump file or not

See the manual page for details (`man ./docs/f5c.1' or https://f5c.page.link/man).`

**Comment by hasindu2008** [comment]
oooh. I have forgotten to update the documentation and the command help. The option is `--pore r10`.
Are you using FAST5 or BLOW5 as input? If you use BLOW5, the pore will be auto-detected even if you do not specify it.

**Comment by hasindu2008** [comment]
@shuyi122425 

Did it work?

**Comment by shuyi122425** [comment]
Sorry, we currently do not have access to the R10 data for the analysis. Once I try to run, I will keep you updated with the results.
And I am also confused about this reference current data( model kmer; model_mean; model_stdv), R10 and R9 use the same set? Because the pore protein arrangement of R10 seems to be different from that of R9.

**Comment by shuyi122425** [comment]
Sorry, I found out the document about r10.4.1_400bps.nucleotide.9mer.model in training new models for f5c using Nanopolish train page. Very detailed instructions!

**Comment by hasindu2008** [comment]
Hi

The models are quite different. The trained models are built into f5c inside https://github.com/hasindu2008/f5c/blob/master/src/model.h. Yes, That link you found tells how exactly the training was done and provides links to the models in text format.

If you want some R10 data, we recently put this open dataset here.
https://github.com/GenTechGp/gtgseq/blob/main/docs/data.md

**Comment by hasindu2008** [comment]
Closing the issue. Feel free to reopen if you have additional questions.
