### ISSUE TITLE
pod5 support instead of fast5

### ISSUE THREAD

**Issue by jolespin** [hasindu2008/f5c#139]
Nanopore has moved away from fast5 format and been using their own format (pod5). 
A new sequencing file format, pod5, that is designed to replace fast5 and enable faster file writing. This supports increasing device outputs and accuracy, enabling smaller raw data file sizes and streamlining downstream analysis. 

* https://nanoporetech.com/about-us/news/oxford-nanopore-delivers-technology-update-annual-london-calling-conference-bringing
* https://github.com/nanoporetech/pod5-file-format
* https://pod5-file-format.readthedocs.io/en/latest/
* https://github.com/nanoporetech/pod5-file-format/blob/master/python/pod5/README.md

**Comment by hasindu2008** [comment]
Hi @jolespin 

Thank you very much for the ping.  Yeh, we had a look at pod5.
As you might already know, the problem with FAST5 performance and size, we already solved two years ago using our own file format called SLOW5/BLOW which is now quite mature:

- https://github.com/hasindu2008/slow5tools and https://hasindu2008.github.io/slow5tools/
- https://github.com/hasindu2008/slow5lib and https://hasindu2008.github.io/slow5lib/
- https://hasindu2008.github.io/slow5lib/pyslow5_api/pyslow5.html
- https://hasindu2008.github.io/slow5specs/
- https://www.nature.com/articles/s41587-021-01147-4
- https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-02910-3
- https://academic.oup.com/bioinformatics/article/39/6/btad352/7186500

S/BLOW5 has the same or better performance/file size for both reading and writing compared to POD5. And, SLOW5 has far more advantages than POD5, in terms of simplicity, compatibility, minimal dependencies, reliability and so on.  f5c was the first bioinformatics tool to support S/BLOW5 format and this feature was available a long time ago. 
For FAST5, we simply convert to a merged BLOW5 file and use the --slow5 option in  f5c.  Similarly what we are envisioning for POD5 is to provide a POD5->S/BLOW5 converter, which the initial prototype is here  https://github.com/Psy-Fer/blue-crab. Note that ONT keeps changing the POD5 format and this does not work on the latest POD5 files, so @Psy-Fer is actively working on this and you should see a release soon, hoping ONT does not keep doing ad-hoc changes to POD5 in the coming months. 

What do you think @jolespin about this approach?

**Comment by jolespin** [comment]
That definitely seems like the most straightforward approach.  Is POD5 an official ONT format?

**Comment by hasindu2008** [comment]
Yes, POD5 is the upcoming official format from ONT to replace FAST5.  As I understand their focus is more on writing and instrument requirements. Whereas in S/BLOW5 which is community-focused, the emphasis is on reading performance, simplicity, compatibility etc. 

It seems like POD5 is predominantly catering to Python programmers. There is no C API. There is a C++ API which seems to be yet incomplete to me, with no documentation yet. And there are so many dependencies like Apache Arrow and Boost which are not too easy to compile from scratch if included in a project like f5c (FAST5/HDF5 was actually better in this sense as the HDF5 library is c99 compatible without extra dependencies). 

So we thought that using ONT's Python API for POD5 to write a Python-based convert to S/BLOW5 is the most sensible approach for programmes such as f5c as then the burden of having this complex POD5 structure and dependency issues can be put onto ONT's API itself.

**Comment by jolespin** [comment]
Yea that makes a lot of sense!  Hopefully they will create some APIs you can use further down the line. Sounds like having the conversion in the backend would be a great placeholder for people using f5c and then eventually when the APIs are available you can swap it out with a new implementation.

**Comment by Psy-Fer** [comment]
That is the goal, or they just give up on pod5 and adopt slow5 :rofl:

**Comment by hasindu2008** [comment]
@jolespin 

Blue crab is feature complete now (hope the future changes in POD5 are backward compatible) - can convert BLOW5<-POD5 back and forth. https://github.com/Psy-Fer/blue-crab. Conversion is pretty fast, so it adds very limited overhead.
