### ISSUE TITLE
Generation of r9.4_450bps.cpg.6mer.template.model

### ISSUE THREAD

**Issue by ShelaLJJ** [hasindu2008/f5c#142]
Hi,

Thank you for developing this tool! It is very useful
May I ask where are the files in r9_models from? For example, where can I get the model file like this one: r9.4_450bps.cpg.6mer.template.model? And can I use f5c to detect base mutations?

Thanks!
Shela

**Comment by hasindu2008** [comment]
Hi Shela

Those models are here: https://github.com/hasindu2008/f5c/tree/master/test/r9-models. 
Those models are also built-in to f5c, so there is no need to manually specify them for a typical use case. Could you tell me what you're trying to achieve?

You can use f5c eventalign, which produces signal-to-reference alignment and can be potentially used for base mutations. Again, I might need some context of what you are trying to achieve, to give an exact answer.

**Comment by ShelaLJJ** [comment]
Thank you very much for your help! I am trying to detect the base substitutions of Adenosines to Guanosines and Adenosines to Inosines, I will try f5c eventalign then.

Best,
Jijun

**Comment by hasindu2008** [comment]
eventalign output is documented here which may help https://hasindu2008.github.io/f5c/docs/output#eventalign.
Feel free to ask anything if you are stuck with something. happy to help.

**Comment by hasindu2008** [comment]
Closing the issue. Feel free to reopen if you have additional questions.
