### ISSUE TITLE
question about methylation detection

### ISSUE THREAD

**Issue by huawen-poppy** [hasindu2008/f5c#143]
Hello! Thanks for the great tool! It is very fast! 

I am trying to use f5c to detection the methylation on my non-human species. But I don't have my own custom nucleotide k-mer model file. I am wondering would this be a problem?

Thank you very much for your time!

**Comment by hasindu2008** [comment]
F5c models are generic and are independent of the species.  If you come across any issues when using default models?

**Comment by huawen-poppy** [comment]
Thanks for your response! I am still running the methylation calling process. I check the output file. It is still empty after running the program for 2 hours. Is it normal?

**Comment by hasindu2008** [comment]
Is it printing any log messages to the standard error? By two hours, data should be written to the output by now. So it is not normal.

**Comment by huawen-poppy** [comment]
Yes, the log message looks like:
![image](https://github.com/hasindu2008/f5c/assets/70507602/ef676dbc-be67-40b7-a07b-91db2231d48d)

**Comment by hasindu2008** [comment]
A few questions to help me debug.
Aren't there any messages at the end telling 512 entries processed? 
Is your data dna or rna?
Can you send the command you issued?

**Comment by huawen-poppy** [comment]
The command I used is 
`f5c call-methylation -b aligned.bam -g aip.genome_models.no_isoforms.no_duplication.mRNA.fa -r combind_all.fastq > result_methylation.tsv`

my data is RNA

at the end there isn't any message telling 512 entries processed. The final message is [get_rank::WARNING]ESC[1;33m A None ACGT base found : UESC[0m

**Comment by hasindu2008** [comment]
If it is rna, you should provide --rna option. However, only the f5c eventalign model supports rna. Methylation models for RNA are not available.

**Comment by huawen-poppy** [comment]
I see. Thank you!
