### ISSUE TITLE
How to interpret the 'NNNNN' in the 'model_kmer' column of eventalign?

### ISSUE THREAD

**Issue by zhongzhd** [hasindu2008/f5c#149]
<img width="838" alt="image" src="https://github.com/hasindu2008/f5c/assets/71424789/7d98a6cc-99d6-413e-bb26-9dd9ed28eb9c">
hello, I would like to understand how to interpret the presence of 'NNNNN' in the 'model_kmer' column in eventalign, why this situation occurs, and how we should handle it. Thanks.

**Comment by hasindu2008** [comment]
Hello @zhongzhd 

The NNNNN in f5c has the same meaning as that in nanopolish. See if https://github.com/jts/nanopolish/issues/438 and https://github.com/jts/nanopolish/issues/264 answer your question?
