### ISSUE TITLE
Some questions about f5c

### ISSUE THREAD

**Issue by JeremyQuo** [hasindu2008/f5c#151]
Dear developer,  f5c is a supportive and user-friendly program compared to others.
I built a program called nanoCEM for showcasing purposes based on f5c re-squiggle, but I have encountered some issues recently. 
I'm here to ask some question
I have some specific details questions I'd like to ask.

1. In my observation, normalization is crucial to make two data sets comparable, as their raw signals may have significant differences. However, currently, the eventalign tool does not provide such an option. Consequently, I have written my code to normalize the results of resquiggling and align them to the reference. I want to inquire if there are any plans to include this option in future versions of eventalign.
2. During the process of resquiggling, I noticed that the event length in the PAF file is slightly shorter by approximately 8 bases compared to the length after basecalling. I'm wondering why this discrepancy exists. While I understand that f5c's algorithm assigns the current index to the last base in a 5-mer, allowing the first four bases to potentially mismatch the current, having an 8-base difference exceeds the expected 4-base discrepancy. Could you please explain the reason behind this?

Thank you very much for your support

**Comment by JeremyQuo** [comment]
Here is the example of one read.

In paf file:

edba3d28-323d-47ce-94c7-fa45d3751990    6543    802     6485    +       edba3d28-323d-47ce-94c7-fa45d3751990    367     0       367     367     367     255     sc:f:0.878083   sh:f:5.024105   ss:Z:6,26,7,9,7,14,7,15,5,16,5,18,17,12,16,8,20,23,7,20,64,23,24,13,7,9,6,23,3,33,12,5,8,9,33,8,14,12,11,13,13,18,11,6,17,3,6,9,15,7,35,7,13,20,10,4,5,18,15,6,4,23,30,8,52,4,5,4,3,49,8,8,18,10,3,7,57,5,41,9,12,15,4,42,11,14,10,10,27,10,32,13,3,48,12,5,6,21,35,7,17,25,6,7,11,17,15,6,8,8,3,8,38,27,55,5,63,5,18,40,8,25,30,9,50,15,6,5,8,3,8,305,10,20,19,14,9,40,10,7,44,13,30,7,6,5,15,23,11,18,5,21,3,18,14,9,7,3,19,25,7,11,27,11,13,9,11,11,16,21,4,4,8,21,27,9,20,9,5,22,64,20,6,8,7,42,7,6,7,4,3,12,5,10,7,10,44,4,6,9,3,6,57,11,5,22,27,40,6,6,7,5,57,20,24,3,8,3,45,10,6,9,8,10,23,9,9,7,8,5,5,13,4,8,33,8,6,9,22,8,10,8,3,9,11,12,3,8,40,14,16,7,21,19,4,12,19,12,13,8,8,15,16,6,10,5,10,19,73,17,13,5,3,37,4,28,17,3,10,7,13,9,12,6,6,6,18,12,5,12,13,3,28,3,10,6,7,7,6,5,12,16,12,11,14,5,12,8,15,10,8,6,12,14,24,28,30,8,9,25,11,8,22,10,4,6,10,10,31,11,25,5,21,4,4,5,5,8,14,10,5,16,36,7,8,56,47,9,50,52,13,7,33,8,24,5,9,15,11,7,17,5,31,8,16,10,21,

In fastq,
@edba3d28-323d-47ce-94c7-fa45d3751990
ACAGGGAATCCCATTTTAATAATGTATCGTATTATTGGGGGCTCGTTGATATCCTTATCTATACGCCCACGATTTAGGGCGGATCTCATACGAAGATAAGAGATTGATGTTTTTATACGGCTTTTTTAACAATATGTAGTATAACATAAGAAACATGTTGCCAAATGTTGGGCCGCGTGCATAAAGTGAAAGAATTAAGTGTTATAAAATCTGCTTACAGGGGAAACAAAATTACTATCCAGAAACCATCGAAGACATTGAAATGTTTACGTTACAAAAACGTGACACCCTTTTTCAGACCATAAGCAATCACCAGCTTTCCTTCACGTATGGTAAGAAGAAAAAGTAACCCTCATATATTATAAAACTCCATAC

**Comment by hasindu2008** [comment]
Hi 

Glad to hear you found f5c was easy to use. 

1. eventalign performs normalisation too. Perhaps I did not understand your question correctly. Do you refer to the f5c resquiggle or f5c eventalign in this question? Can you tell me the commandline you are using?
2. Is this DNA or RNA data? Perhaps this is DNA R10 data where the k-mer size is 9?

**Comment by JeremyQuo** [comment]
Thanks for your information.

Question 1 means to rescale by NormSignal=(RawSignal−ShiftScale)/scale from tombo did ( https://nanoporetech.github.io/tombo/resquiggle.html).
While the value  is supposed to be around -5 to 5, in eventalign in f5c(event_level_mean and model_mean) is around 0-120

CMD:
f5c eventalign --slow5 ./WGS1.blow5 -b WGS1.bam -g ../asfv.fa -r WGS1.fastq > events.tsv

2. R10 DNA, Thanks for your information I gotta it. How to identify the k-mer size from the input data?

**Comment by JeremyQuo** [comment]
Thanks for your information.
I tried  --scale-events and found it still did not satisfy my requirement, but it's ok  I can write a new function to index and rescale it by the f5c resuqiggle result and k-mer size from your answer.

Additionally, the last question, is the k-mer-model only defined in nanopolish/f5c? Has it been mentioned elsewhere, such basecall software (guppy/dorado) or Tombo.  I previously believed that he was consistently "5" because during nanopore sequencing, a pore typically retains approximately five bases at a given time.

**Comment by hasindu2008** [comment]
Actually, now I am a bit confused as you mention about f5c requiggle and f5c eventalign interchangeably.  Can you clarify if your question originally was about f5c resquiggle or f5c eventalign?

- f5c resquiggle simply performs the alignment of a signal to a basecalled read
- f5c event align performs the alignment of a signal to the reference

Is your intended usecase signal to read or signal to reference alignment?

k-mer model is not just limited to nanopolish/f5c. It was first available in early ONT programs and ONT makes pore models available through https://github.com/nanoporetech/kmer_models. Guppy/Dorado uses neural network models, so they do not directly use such a k-mer model, but apparently remora inside Dorado and Guppy does! - what I saw here and there based on what ONT folks say. I have not much looked into Tombo (every time I tried to install it, I ran out of patience as it keeps installing hundreds of libraries and eventually failing), but I have a vague memory that Tombo uses a pore model too. 

In R9 pores, yeh, typically the pore retains ~5 bases at a given time. However in R10, the pore structure is different and is said to be longer. So this is why 9-mer is more suitable for R10 in my understanding.  But we should keep in mind that, even though a pore can contain ~X bases, the bases close to the pore can still affect the current. So, even if the pore can retain 5 bases, we can rely on a 6-mer or 7-mer model to include the effect of those nearby bases. My knowledge of ONT's pores or their characteristics is also limited, so I might not be fully correct either. But it is very hard to get any useful information about these pores and models from ONT, which I have tried a few times, only to get some vague incomplete answers.

**Comment by JeremyQuo** [comment]
Thank you for your generous response. I am looking to find features corresponding to the ` reference sequence`. However, since the eventalign function does not provide me with the expected features I want, I choose to use the result from re-squiggle and alignment results to re-index by myself and find what I need.

Tombo indeed has had challenging installation issues, and it is no longer actively updated. However, since I have been using it and have resolved its environment problems, I can help with the installation if needed.

Thank you very much for the introduction to k-mer models. I now have a better understanding.

**Comment by hasindu2008** [comment]
@JeremyQuo 
What I would suggest is to use the f5c eventalign (which is much more accurate when aligning to the reference than simply projecting the resquiggle) to get the signal coordinates of the alignment and then use that information to normalise the way you wish. Could you tell how you process the resquiggle output currently? 
1. Do you use the tsv output or paf output?
2. Do you access the raw signal from the indices based on resquiggle output?
Then I can suggest the easiest path towards getting something similar in eventalign.

**Comment by JeremyQuo** [comment]
Cause I would like to have support for both `Tombo` and `f5c`, and I would prefer their normalizations to be similar.

In the articles I have previously read, such as `nanom6A`,
1. They utilized `mean/median/std/dwell time` of each event. However, nanopolish/f5c does not provide all of these features。
2. The rescaled values of their mean/median range between` -5` and` 5`. Even when I added the` --scale-events` option, the values did not change. 
This is why I am not using eventalign.

For how I use the result from f5c resquiggle,

1. Rescaling the entire current signal to match the Tombo signal normalization formula (https://nanoporetech.github.io/tombo/resquiggle.html).
2. Recomputing the event features for each basecall sequence, including mean, median, standard deviation, and dwell time from the index in paf file.
4. Mapping the basecall sequence to the reference sequence using the CIGAR string from the Minimap2 BAM file like below.
![image](https://github.com/hasindu2008/f5c/assets/76717431/65242fb4-25cb-44c0-be0a-a820e7c9b6b7)

**Comment by JeremyQuo** [comment]
Thanks for your information. I will try to convert to eventalign and try Squigualiser

**Comment by JeremyQuo** [comment]
I checked the new log of f5c 1.4 and the k-mer length confused me, what's the final kmer length of rna004? 5 or 9?

**Comment by hasindu2008** [comment]
The builtin model for rna004 in f5c was decided to be 9 to match with the ONT's kmer size for rna004.  Note that this is for the new RNA rna004 flowcell. Previous r9 (rna002) model remains to be 5mer. Hope it is clear?

**Comment by JeremyQuo** [comment]
thanks
