### ISSUE TITLE
Using nanopolish polyA with f5c index error

### ISSUE THREAD

**Issue by kir1to455** [hasindu2008/f5c#152]
Hi,
I have encountered the same problem as below.
#125 
I created readdb using the following code.
`echo -e "*\t/public3/hjliang/SARS_CoV_2/slow5/CoV2_A549_1/CoV2_A549_1.blow5" > /public3/hjliang/SARS_CoV_2/fastq_file/CoV2_A549_1_chrSCV.fastq.index.readdb`
![image](https://github.com/hasindu2008/f5c/assets/87375686/9b84280d-309f-4bcb-904c-8e2f6703725a)

And my nanopolish polya code:
`nanopolish polya --reads CoV2_A549_1_chrSCV.fastq --bam ${subset_bam_dir}/${bbase}.SARS.${orfname}.sorted.bam --genome ${index_dir}/SARS-CoV-2.fa --threads 40 > ${PolyA_dir}/${bbase}.${orfname}.poly.tsv`

I got the result show all is -1.0 and the last column are all READ_FAILED_LOAD.
My nanopolish version is 0.14.0.
Did I make a mistake somewhere?

Best wishes,
Kirito

**Comment by hasindu2008** [comment]
Is this R9.4 data or latest R10.4 data?

**Comment by kir1to455** [comment]
Direct RNA-sequencing data with R9.4.1

**Comment by hasindu2008** [comment]
I think I know the issue, there was a bug that affected the SLOW5 with polyA which was fixed a bit later after the v0.14.0 [here](https://github.com/jts/nanopolish/commit/07cb03deb49323b439ed84641b3352d850ce2812). Would you be able to try compiling nanopolish latest commit from the master branch?

**Comment by kir1to455** [comment]
Hi, I have compiling nanopolish latest commit and it shows the correct results.
Thanks for your help!

Best wishes,
Kirito
