### ISSUE TITLE
f5c index : num reads and num reads with path to fast5  don't match

### ISSUE THREAD

**Issue by sachingadakh** [hasindu2008/f5c#153]
Hello, 
  Thank you for creating this tool, as it processes the Nanopolish functions quite fast using f5c toolkit.
Let me discuss my issue from the beginning. I have already processed (index, align, call methylation) two samples successfully with Nanopolish where indexing numbers matched, and there were zero bad fast5. 
But when I was performing call methylation on my 3rd sample, I received the following summary : 
Total reads: 2741796, unparseable: 0, qc fail: 3457, could not calibrate: 2766, no alignment: 73672, bad fast5: 7315
Then out of curiosity I checked the Nanopolish index result of this 3rd sample and I found num reads and num reads with a path to fast5 don't match;  **num reads: 2767944, num reads with path to fast5: 2760575**. 

I saw your suggestions in some of the issues on Nanopolish github page and decided to perform indexing using f5c on my 3rd sample, and I received exact same results as follows : 

[find_all_fast5] Looking for fast5 in ../passed_fast5_allflowcell514/
[f5c_index_iop] 692 fast5 files found - took 0.002s
[f5c_index_iop] Spawning 100 I/O processes to circumvent HDF hell
[f5c_index_iop] Parallel indexing done - took 355.034s
[f5c_index_merge] Indexing merging done - took 3.343s.
[readdb] **num reads: 2767944, num reads with path to fast5: 2760575**
[main] Version: 1.3
[main] CMD: f5c index -t 100 --iop 100 -d ../passed_fast5_allflowcell514/ HG00514_ONT10X_dorado.fastq
[main] Real time: 756.983 sec; CPU time: 6988.048 sec; Peak RAM: 0.757 GB

I am wondering if this mismatch of numbers in indexing is causing the bad fast5 during methylation calling in my 3rd sample.
Can you please guide me on what I can do in this scenario? 

I am attaching the screenshot head of readdb file for your reference
![image](https://github.com/hasindu2008/f5c/assets/44431816/282f80c6-c18d-49b2-b9d6-b5680bdfd417)

Thank you

**Comment by hasindu2008** [comment]
@sachingadakh Yes, some of your fast5 files may be malformed and nanopolish/f5c index ignores those files during the indexing step. That is why the readdb has less number of entries as well as the reason for bad_fast5 in the call-methylation.
If you are curious about what has happened to those fast5 files and want to exactly see if they could be recovered, you may try converting your fast5 dataset to BLOW5 using [slow5tools f2s command](https://github.com/hasindu2008/slow5tools). It is likely that slow5tools will error out with a informative error message when it hits one of those malformed FAST5 files.

**Comment by sachingadakh** [comment]
Hello Hasindu,
  Thank you for your suggestions. I followed your suggestions on my two samples, which reported a mismatch of numbers in indexing and ultimately causing a bad fast5 earlier when working with Nanopolish tool.
Now  I converted fast5 to blow5 using slow5tools :  

/home/sachin/slow5tools-v1.1.0/slow5tools f2s fast5_data/ -d blow5/
[list_all_items] Looking for '*.fast5' files in fast5_data/
[f2s_main] 1687 fast5 files found - took 0.005s
[f2s_main] Just before forking, peak RAM = 0.000 GB
[f2s_iop] 8 proceses will be used.
[f2s_iop] Spawning 8 I/O processes to circumvent HDF hell.
[f2s_child_worker::INFO] Summary - total fast5: 211, bad fast5: 0
[f2s_child_worker::INFO] Summary - total fast5: 211, bad fast5: 0
[f2s_child_worker::INFO] Summary - total fast5: 211, bad fast5: 0
[f2s_child_worker::INFO] Summary - total fast5: 210, bad fast5: 0
[f2s_child_worker::INFO] Summary - total fast5: 211, bad fast5: 0
[f2s_child_worker::INFO] Summary - total fast5: 211, bad fast5: 0
[f2s_child_worker::INFO] Summary - total fast5: 211, bad fast5: 0
[f2s_child_worker::INFO] Summary - total fast5: 211, bad fast5: 0
[f2s_main] Converting 1687 fast5 files took 13059.050s
[f2s_main] Children processes: CPU time = 35815.294 sec | peak RAM = 0.059 GB
[main] cmd: /home/sachin/slow5tools-v1.1.0/slow5tools f2s fast5_data/ -d blow5/
[main] real time = 13059.056 sec | CPU time = 0.009 sec | peak RAM = 0.006 GB

You can see 0 bad fast5 reported by slow5tools. It produced exact number of blow5 as given input of fast5 i.e 1687.
Here I want to ask one question: does slow5tools further compress fast5 to blow5?, given the size of blow5 is smaller than fast5. so I assumed fast5 are not malformed and recovered

Further I merged all blow5 into single blow5 in order to f5c index as follows : 
f5c index -t 100 --slow5 GM19240_ONT10X_dorado.blow5 GM19240_ONT10X_dorado.fastq 
[index_main] Slow5 index built - took 828.980s
[index_main] Fasta index built - took 728.451s
[main] Version: 1.3
[main] CMD: f5c index -t 100 --slow5 blow5/onlyblow/GM19240_ONT10X_dorado.blow5 f5c_index/GM19240_ONT10X_dorado.fastq
[main] Real time: 1558.236 sec; CPU time: 11275.590 sec; Peak RAM: 2.032 GB

Here f5c index using blow5 didn't produce readdb and, therefore not report "num reads and num reads with path to fast5".
whole f5c index using fast5 had reported following summary
[readdb] num reads: 6767228, num reads with path to fast5: 6742291


Then I proceeded to f5c call-methylation, which started with the following flags as it was calculating methylation. 

[meth_main::INFO] Default methylation tsv output format is changed from f5c v0.7 onwards to match latest nanopolish output. Set --meth-out-version=1 to fall back to the old format.
[init_core::INFO] builtin DNA R9 nucleotide model loaded
[init_core::INFO] builtin DNA R9 cpg model loaded
[slow5_idx_get::ERROR] Read ID 'd6a9401e-90df-4e20-a5e3-ee0326775d75' was not found. At src/slow5_idx.c:441
[read_slow5_single::WARNING] Slow5 record for read [d6a9401e-90df-4e20-a5e3-ee0326775d75] is unavailable/unreadable and will be skipped
[slow5_idx_get::ERROR] Read ID 'ec784811-d0c2-41d5-b4c3-0e7abbdae0d5' was not found. At src/slow5_idx.c:441
[read_slow5_single::WARNING] Slow5 record for read [ec784811-d0c2-41d5-b4c3-0e7abbdae0d5] is unavailable/unreadable and will be skipped
[meth_main::21.522*0.55] 467 Entries (5.0M bases) loaded
[pthread_processor::23.131*2.41] 467 Entries (5.0M bases) processed
[meth_main::32.143*1.77] 483 Entries (5.0M bases) loaded
[pthread_processor::33.589*2.96] 483 Entries (5.0M bases) processed
[meth_main::43.308*2.32] 512 Entries (4.8M bases) loaded
[pthread_processor::45.021*3.34] 512 Entries (4.8M bases) processed
[slow5_idx_get::ERROR] Read ID '2497e8e7-a10e-4d94-b3bf-c6142b861ce1' was not found. At src/slow5_idx.c:441
[read_slow5_single::WARNING] Slow5 record for read [2497e8e7-a10e-4d94-b3bf-c6142b861ce1] is unavailable/unreadable and will be skipped

Ultimately summary of f5c call-methylation is as follows.

[meth_main] skipped unmapped: 0, skipped secondary: 0, skipped low_mapq: 2713132
[meth_main] total entries: 6814047, qc fail: 3459, could not calibrate: 7776, no alignment: 175305, bad reads: 25187
[meth_main] total bases: 63028.8 Mbases
[meth_main] Data loading time: 25757.974 sec
[meth_main]     - bam load time: 2282.219 sec
[meth_main]     - fasta load time: 19801.900 sec
[meth_main]     - slow5 load time: 3657.550 sec
[meth_main] Data processing time: 17923.823 sec
[meth_main] Data output time: 855.020 sec
[meth_main::INFO] Performance bounded by file I/O. File I/O took 7834.150 sec than processing
[main] Version: 1.3
[main] CMD: f5c call-methylation -r GM19240_ONT10X_dorado.fastq -b GM19240_ONT10X_dorado.sorted.bam -g hg38_upper2.fa --slow5 GM19240_ONT10X_dorado.blow5 -t 200 
 
So, since slow5tools f2s and f5c index using blow5 didn't report about ignored fast5 but f5c call-methylation reported bad reads such as 25187 but f5c index using fast5 reported (num reads: 6767228, num reads with path to fast5: 6742291) 6767228−6742291 = 24937. So here there is a difference in bad reads reported by f5c index with fast5 and f5c call-methylation with blow5.

Anyway finally I want to ask, what could be the reason for these bad reads and any solution to recover them.
Thank you

**Comment by hasindu2008** [comment]
It seems like Dorado by default enables read splitting. However, as you can see only 25187/6814047*100=0.37% of reads are affected.  There might be an option to disable it in Dorado, but it is just too few reads that you are loosing, which I think would not affect that much (unless your research question primarily involves duplex read)

**Comment by sachingadakh** [comment]
Sure. Thank you very much for all questions and solving the issue. I am much obliged. Cheers
