### ISSUE TITLE
f5C Resquiggle Memory Problems

### ISSUE THREAD

**Issue by miles-jon** [hasindu2008/f5c#159]
Hello, 

I am trying to use the f5C resquiggle command as part of the data preparation for squigualiser. The system I am using has 32 GB RAM, an 8GB Graphics Card (NVIDIA GeForce GTX 1070 ) and a 16 core CPU (AMD Ryzen 7 1700 Eight-Core Processor). However, whenever I try to use f5c, I get the following error message:

 nathan@nathan-X370GTN:~/squig_workspace/test$ /home/nathan/f5c-v1.4/f5c_x86_64_linux resquiggle -x desktop -c ./test.fq test_cat.blow5 --rna -o test.paf
[set_opt_profile] max-lf: 5.0, avg-epk: 2.0, max-epk: 5.0, K: 768, B: 6.2M, t: 12, ultra-thresh: 100.0k, iop: 4
[slow5_idx_init::INFO] Index file not found. Creating an index at test_cat.blow5.idx'.
[slow5_idx_build::ERROR] Failed to allocate memory: Cannot allocate memory At src/slow5_idx.c:276
[sig_handler::ERROR] I regret to inform that a segmentation fault occurred. But at least it is better than a wrong answer.

I have tried different paths, different -x argument profiles (from lowest to highest), with and without cuda, and adjusting the -K and -B arguments manually but have not found a combination that works. I am not sure why this hasn't  

I am using version 1.4, have tried version 1.3 and have also tried running the slow5tools command separately but I run into the same issue. 

Is there something I might have missed when installing f5c that makes it unable to use the resources available?

Thanks, 

Jon

**Comment by hasindu2008** [comment]
This is a bit weird thing that is likely to be a bug. How large is the test blow5 file?

**Comment by miles-jon** [comment]
Hello, 

Thank you for your speedy response. 

The blow5 file is 381.1 MB. I made it with slow5tools as described in its own documentation. 

Thanks, 

Jon

**Comment by hasindu2008** [comment]
Would it be possible to upload that file to somewhere and provide a link? Then I could try on my computer to see if I could replicate the issue. Or could you download and run on my tiny test dataset?
```
wget -O test.tgz https://f5c.bioinf.science/f5c_ecoli_2kb_region_test
tar xf test.tgz
cd ecoli_2kb_regionecoli_2kb_region
f5c resquiggle -c reads.fasta reads.blow5 -o test.paf
```
See if this error still comes?

**Comment by miles-jon** [comment]
Hi, 

I tried this and confusingly this worked fine. I will try reinstalling f5c and rebasecalling and remapping my data. Does the fastq data need to be converted to fasta for the process to start off? 

Thanks, 

Jon

**Comment by hasindu2008** [comment]
No, both the FASTQ and FASTA will work.  You can try the following, which is a bit larger test set, rna004 and fastq.

```
wget -O rna.tgz https://f5c.bioinf.science/uhr_rna004_1k
tar xf rna.tgz
cd uhr_rna004_1k/
f5c resquiggle PNXRXX240011_reads_1k.fastq  PNXRXX240011_reads_1k.blow5 -c -o a.paf
```
`--rna` can be provided, but this is autodetected for BLOW5 and is unnecessary.

**Comment by miles-jon** [comment]
Hi there, 

Thank you for your responses. Both of your test data sets I re-processed my data and was able to get it working! Not sure if there was some bug introduced in how I processed it or what but I can get through it now. 

Thanks again, 

Jon

**Comment by hasindu2008** [comment]
Closing this issue for now. If you see this error again, feel free to reopen :D
