### ISSUE TITLE
get 5mer output with R10 data

### ISSUE THREAD

**Issue by lyj95618** [hasindu2008/f5c#165]
Hi, 

I have two data sets, one from R9 and the other from R10. From the eventalign.txt, I can tell that R9 is the 5mer model and R10 is the 9mer model. I am wondering it is possible to get 5mer eventalign output with R10 data using `f5c` ? 

Some background of my issue:
I want to use a tool called `xpore` to perform differential modification analysis and it only supports 5mer model for comparison. So with my R10 data which is 9mer model, the eventalign.txt is not compatible with the R9 eventalign output. 

Thank you very much!
Laur

**Comment by hasindu2008** [comment]
Hello Laur

Isn't xpore only for direct-RNA? The reason why I am asking is, r10 is only for DNA. Perhaps you meant the rna004 pore? 

If that is the case, you can simply extract the middle 5-mer from the event alignment's 9-mer. The authors of m6Anet and xpore did this strategy for m6anet - @jonathangoeke and @yuukiiwa should be able to answer this.

**Comment by yuukiiwa** [comment]
Hi @lyj95618,

You will have to change the `reference_kmer` and the `model_kmer` columns from 9mers to 5mers:
```
GATAAGGAT --> TAAGG
ATAAGGATT --> AAGGA
```

I will update m6anet this month for converting 9mer to 5mer within.

Thanks!

Best wishes,
Yuk Kei

**Comment by hasindu2008** [comment]
@lyj95618 I hope your question is resolved. If not feel free to reopen this issue.
