### ISSUE TITLE
using phased bam

### ISSUE THREAD

**Issue by edeuse** [hasindu2008/f5c#173]
I intend to use a phased BAM file generated from Pepper-Margin-DeepVariant, with FASTQ sequences extracted from the phased BAM using samtools fastq. 
The resulting methylation calls and frequency data will be utilized with NanoMethPhase tool. 
While I've confirmed that this approach works effectively, I am curious about the differences between using a phased BAM versus an unphased BAM in this context. 
Could you provide insights on the distinctions between the two, and which approach you would recommend for optimal results?

**Comment by hasindu2008** [comment]
Hi

f5c processes each BAM record in the given BAM file independently. So whether it is in a single file or separate files it does not matter. A phased BAM is a kind of a subset of a unphased BAM file if I understand correctly, if so, there should not be a difference.

However, be careful when you extract FASTQ from an aligned BAM file. If the aligner you used performed hard clipping, f5c may not be able to anchor the read to the signal appropriately during the read-to-signal alignment step.

**Comment by edeuse** [comment]
Thank you. 
After reviewing the haplotagged BAM file generated by Pepper-Margin-DeepVariant, it appears that there are no hard-clipped reads. Following your recommendation, we have decided to use the aforementioned haplotagged BAM file as the input for the f5c analysis. 
Thank you for providing such valuable resources.
