### ISSUE TITLE
Clarification on reference type for eventalign

### ISSUE THREAD

**Issue by Euchiz** [hasindu2008/f5c#174]
Hi f5c developers,

I am currently using the `eventalign` function in f5c for my data analysis and wanted to clarify whether I should use a BAM file aligned to a genome reference or a transcriptome reference.

My main concern is whether f5c takes introns into consideration when performing the alignment, or is it better suited for alignments against a transcriptome reference where introns are not present?

I would appreciate any guidance on which reference type is recommended for use with `eventalign` to ensure accurate results.

Thank you for your time and for developing this useful tool!

**Comment by hasindu2008** [comment]
Hello
Please use the alignment against the transcriptome.

**Comment by Euchiz** [comment]
Got it. Thanks for the guidance!
