### ISSUE TITLE
obtaining the read ID in the eventalign file

### ISSUE THREAD

**Issue by peterthorpe5** [hasindu2008/f5c#175]
Dear f5c,

thank you for your super fast implementation. 

I am trying to get the original read_ID(s) for data in the eventalign file. Is there a way of getting read_ID, match start stop or some metrics I can then use to match against the bam file? Why(?): I am trying to interogote specific reads that have an m6a modification as predicted by m6anet (which uses the eventalign file)... 

The eventalign file does not quite have enough information to overlap the bam alignments with it. Or maybe it does and I am being daft?

  contig position reference_kmer read_index strand event_index event_level_mean event_stdv event_length model_kmer mod
  el_mean model_stdv standardized_level start_idx end_idx
  AT1G01050.1 34 TTACA 14 t 1 78.09 0.995 0.00365 TTACA 79.88 2.10 -0.73 40323 40334
  AT1G01050.1 34 TTACA 14 t 2 76.65 0.874 0.00266 TTACA 79.88 2.10 -1.32 40315 40323
  AT1G01050.1 34 TTACA 14 t 3 80.95 1.438 0.00465 TTACA 79.88 2.10 0.44 40301 40315
  AT1G01050.1 34 TTACA 14 t 4 79.07 1.708 0.00332 TTACA 79.88 2.10 -0.33 40291 40301

If you could please give me some pointers as how I could get the original read_ID for each of these?

regards,

Pete

**Comment by hasindu2008** [comment]
Hello

Could you check if the --print-read-names option is what you are after?

**Comment by peterthorpe5** [comment]
thank you this is useful. I can combine the eventaligns that have the read_index and the nex one using the  --print-read-names  -- thank you. This is useful.

**Comment by peterthorpe5** [comment]
Is it possible to write out both the "--print-read-names "  and the index which is generated for m6anet? As I understand it now, it is one of the other ...

**Comment by peterthorpe5** [comment]
Thank you; that’s very helpful. I have previously generated two eventalign files for each replicate—one with the index and one with the read names. These files are about 200 GB each. Using a small test set (a few MB in size), I can extract the information I need. However, scaling this up would make the runtime infeasible. I will try using the BAM approach to extract the names. Thank you again!

**Comment by peterthorpe5** [comment]
Hi hasindu, I just want to raise this potential issue. Running f5c with the exact same command but with the addition  of --print-read-names for one output files, generate data that is not in the same order. These were generated using the same bam file.  I presume this is not expected? It also, means I cannot take it as a given that the order is based on the read order in the bam file as this is the same bam file.


 head -n 5 index.example
contig  position        reference_kmer  read_index      strand  event_index     event_level_mean        event_stdv      event_length    model_kmer      model_mean      model_stdv       standardized_level      start_idx       end_idx
AT1G01020.1     466     GGCGG   5       t       1       98.26   4.465   0.00631 GGCGG   98.79   8.39    -0.06   35792   35811
AT1G01020.1     466     GGCGG   5       t       2       108.93  5.259   0.00531 GGCGG   98.79   8.39    1.10    35776   35792
AT1G01020.1     466     GGCGG   5       t       3       101.87  4.585   0.00232 GGCGG   98.79   8.39    0.33    35769   35776
AT1G01020.1     466     GGCGG   5       t       4       108.08  4.931   0.03320 GGCGG   98.79   8.39    1.00    35669   35769


head -n 5 readnames.example
contig  position        reference_kmer  read_name       strand  event_index     event_level_mean        event_stdv      event_length    model_kmer      model_mean      model_stdv       standardized_level      start_idx       end_idx
AT1G01010.1     20      CCAGA   7c2a1a9a-2901-44cf-ac71-52f99b65f88d    t       2       74.70   4.069   0.00531 CCAGA   76.22   5.09    -0.27   58578   58594
AT1G01010.1     21      CAGAG   7c2a1a9a-2901-44cf-ac71-52f99b65f88d    t       3       111.81  5.409   0.00564 CAGAG   106.73  5.87    0.79    58561   58578
AT1G01010.1     22      AGAGA   7c2a1a9a-2901-44cf-ac71-52f99b65f88d    t       4       124.33  4.021   0.00232 AGAGA   127.71  5.69    -0.54   58554   58561
AT1G01010.1     22      AGAGA   7c2a1a9a-2901-44cf-ac71-52f99b65f88d    t       5       132.97  1.753   0.00531 AGAGA   127.71  5.69    0.84    58538   58554

rule f5c_eventalign:
    input:
        fastq='data/basecalled/{sample_name}.dna.fastq',
        readdb="data/basecalled/{sample_name}.dna.fastq.index.readdb",
        bam='data/aligned_data/{sample_name}.transcriptome.bam',
        bai='data/aligned_data/{sample_name}.transcriptome.bam.bai',
        ref=ancient(os.path.abspath(config['transcriptome_fasta_fn'])),
    output:
        events='data/f5c/{sample_name}.eventalign.txt'
    threads: 8
    conda:
        'env_configs/f5c.yaml'
    shell:
        '''
        f5c eventalign --rna -t 8 -K 100 -B 1.0M --iop 32 \
          --verbose 1 \
          --scale-events --signal-index \
          -r {input.fastq} \
          -b {input.bam} \
          -g {input.ref} > {output.events}
        '''

rule f5c_eventalign_read_names:
    input:
        fastq='data/basecalled/{sample_name}.dna.fastq',
        readdb="data/basecalled/{sample_name}.dna.fastq.index.readdb",
        bam='data/aligned_data/{sample_name}.transcriptome.bam',
        bai='data/aligned_data/{sample_name}.transcriptome.bam.bai',
        ref=ancient(os.path.abspath(config['transcriptome_fasta_fn'])),
    output:
        events='data/f5c_readnames/{sample_name}.eventalign.txt'
    threads: 8
    conda:
        'env_configs/f5c.yaml'
    shell:
        '''
        f5c eventalign --rna -t 8 -K 100 -B 1.0M --iop 32 --print-read-names \
          --verbose 1 \
          --scale-events --signal-index --print-read-names \
          -r {input.fastq} \
          -b {input.bam} \
          -g {input.ref} > {output.events}
        '''

   
Dr Peter Thorpe
Research Data Analyst/Bioinformatician
School of Life Sciences, University of Dundee
[pthorpe001@dundee.ac.uk](mailto:pthorpe001@dundee.ac.uk)
            [Higher Educational Institution of the Year - The Herald HE Awards 2023](http://uod.ac.uk/sig-strapline)
University of Dundee, Nethergate, Dundee, Scotland, UK, DD1 4HN

**Comment by hasindu2008** [comment]
It is really strange because they should be in the exact order. f5c output is deterministic.
I just checked the following:

```
./f5c eventalign -b uhr_rna004_1k/PNXRXX240011_reads_1k.bam -g uhr_rna004_1k/gencode.v40.transcripts.fa -r uhr_rna004_1k/PNXRXX240011_reads_1k.fastq  --slow5 uhr_rna004_1k/PNXRXX240011_reads_1k.blow5  | cut -f 4 --complement > a.txt
./f5c eventalign -b uhr_rna004_1k/PNXRXX240011_reads_1k.bam -g uhr_rna004_1k/gencode.v40.transcripts.fa -r uhr_rna004_1k/PNXRXX240011_reads_1k.fastq  --slow5 uhr_rna004_1k/PNXRXX240011_reads_1k.blow5 --print-read-names | cut -f 4 --complement > b.txt
diff a.txt b.txt 
```
The diff passed.
Could you first download my test dataset as
```
wget https://f5c.bioinf.science/uhr_rna004_1k -O uhr_rna004_1k.tgz 
tar xf uhr_rna004_1k.tgz 
```
Then run the above three command and see if the diff passes?

By the way, something I forgot was that you can use the --summary a.tsv option to write the summary file which gives the read-index and read-id mapping like below:
```
read_index	read_name	fast5_path	model_name	strand	num_events	num_steps	num_skips	num_stays	total_duration	shift	scale	drift	var
0	925909a9-c022-4695-a4a0-8e6c1971b6f0	slow5	rna	template	575	185	7	382	3.43	5.491	0.873	0.000	1.828
5	c2ea507f-00a0-49cf-88f5-e95a26076651	slow5	rna	template	668	396	14	257	3.21	-6.634	0.950	0.000	1.356
6	e433f84b-10fe-44a1-80cd-9c4100a68454	slow5	rna	template	1270	774	22	473	6.10	-6.327	0.979	0.000	1.353
7
```

**Comment by peterthorpe5** [comment]
This test passes for me. I will try this "--summary a.tsv " to see if it give me what I need. Thank you for your help.
