### ISSUE TITLE
The issue of methylation calling failure in the het deletion sample.

### ISSUE THREAD

**Issue by edeuse** [hasindu2008/f5c#178]
Hello, I have been working with a sample that has a large heterozygous deletion on chromosome 15, where the other allele is methylated. 
However, when performing methylation calling, I found that most of the key CpG sites did not have methylation calls. 
Given the heterozygous deletion, the CpG sites on one allele should exhibit a methylation frequency close to 1. 

Could you help me understand why there are no methylation calls at these CpG sites?

These are the methylation calls.tsv from the het del sample (CpG site we are observing - chr15:24954888-24955907) 
(mean depth of the large del region is 8.x)
![image](https://github.com/user-attachments/assets/0338b553-5556-48fa-b0a2-6d8e8bbe7a7c)

For comparison, I am providing the methylation call file from the NC sample, analyzed using the same pipeline.
(mean depth is 12.x)
![image](https://github.com/user-attachments/assets/8c6f4eea-e29a-40fe-a03e-cc0a80b99316)

**Comment by hasindu2008** [comment]
Hello

It could be due to a several reasons that this could happen. Let us try to narrow it down. Would you mind doing f5c call-methylation with `-w  chr15:24954000-24956000` option for the two datasets above and provide me with the stderr output of f5c that gives the number of reads that failed the filters? 
example:
```
[meth_main] skipped unmapped: 1, skipped secondary: 0, skipped low_mapq: 0
[meth_main] total entries: 143, qc fail: 0, could not calibrate: 0, no alignment: 0, bad reads: 0
```

**Comment by edeuse** [comment]
Hi 
Thank you for your advice. The issue was eventually resolved by using the GridIon live basecalling files. It seems that the problem arises when using Dorado basecalling files. Once again, thank you for your help.
