### ISSUE TITLE
Switching from nanopolish to f5c, worse m6a-callers performance/different output files

### ISSUE THREAD

**Issue by BrendanBeahan** [hasindu2008/f5c#186]
Hello,

I have moved over to f5c from nanopolish in order to utilize RNA004/pod5. However, when I converted my fast5 files from an RNA002 experiment to pod5 and then blow5 format, and then ran them through f5c I appear to generate rather differently sized files. The performance of my downstream m6A-caller tools using these files also apepars to be worse. 

I am wondering if I may have done something wrong in setting the flags on f5c? 

Here is the current Nextflow pipeline process that I have for nanopolish:

`
// Resquigling with nanopolish for each condition
process nanopolish1 {
    input:
		tuple val(condition), val(sample) from minimap2_nanopolish1

		each file('transcriptome.fa') from transcriptome_fasta_nanopolish1
		each file('transcriptome.fa.fai') from transcriptome_fai_nanopolish1

		each file('genome.fa') from genome_fasta_nanopolish1
		each file('genome.fa.fai') from genome_fai_nanopolish1
    output:
    	tuple val(condition), val(sample) into nanopolish1_xpore
    	tuple val(condition), val(sample) into nanopolish1_nanocompore1
    	tuple val(condition), val(sample) into nanopolish1_yanocomp1
    	tuple val(condition), val(sample) into nanopolish1_m6anet1

    script:
    if(params.nanopolish1)
    """
		mkdir -p ${params.resultsDir}/${condition}/${sample}/nanopolish/
		#mkdir -p ${params.resultsDir}/${condition}/${sample}/nanopolish/genome/
		mkdir -p ${params.resultsDir}/${condition}/${sample}/nanopolish/transcriptome/

		/usr/bin/nanopolish/nanopolish index -d ${params.resultsDir}/${condition}/${sample}/FAST5/ ${params.resultsDir}/${condition}/${sample}/FASTQ/singleReadsFASTQ.fastq

		/usr/bin/nanopolish/nanopolish eventalign --reads ${params.resultsDir}/${condition}/${sample}/FASTQ/singleReadsFASTQ.fastq --bam ${params.resultsDir}/${condition}/${sample}/transcriptomeAlignment/minimap.filt.sort.bam --genome transcriptome.fa --samples --signal-index --scale-events -n --summary ${params.resultsDir}/${condition}/${sample}/nanopolish/transcriptome/summary.txt --threads ${task.cpus} > ${params.resultsDir}/${condition}/${sample}/nanopolish/transcriptome/eventalign_readName.txt

		/usr/bin/nanopolish/nanopolish eventalign --reads ${params.resultsDir}/${condition}/${sample}/FASTQ/singleReadsFASTQ.fastq --bam ${params.resultsDir}/${condition}/${sample}/transcriptomeAlignment/minimap.filt.sort.bam --genome transcriptome.fa --signal-index --scale-events --summary ${params.resultsDir}/${condition}/${sample}/nanopolish/transcriptome/summary.txt --threads ${task.cpus} > ${params.resultsDir}/${condition}/${sample}/nanopolish/transcriptome/eventalign_readIndex.txt

    """
	else
	"""
        echo "Skipped"
    """
}`

And here is the Nextflow pipeline process that I have for f5c:

`
// Resquigling with f5c for each condition
process f5c {
    input:
		tuple val(condition), val(sample) from minimap2_f5c1

		each file('transcriptome.fa') from transcriptome_fasta_f5c1
		each file('transcriptome.fa.fai') from transcriptome_fai_f5c1

		each file('genome.fa') from genome_fasta_f5c1
		each file('genome.fa.fai') from genome_fai_f5c1
    output:
    	tuple val(condition), val(sample) into f5c1

    script:
    if(params.f5c)
    """
		mkdir -p ${params.resultsDir}/${condition}/${sample}/f5c/
		mkdir -p ${params.resultsDir}/${condition}/${sample}/f5c/transcriptome/

		f5c_x86_64_linux index --slow5 ${params.resultsDir}/${condition}/${sample}/BLOW5/mergedBLOW5/merged.blow5 ${params.resultsDir}/${condition}/${sample}/FASTQ/singleReadsFASTQ.fastq

		f5c_x86_64_linux eventalign --reads ${params.resultsDir}/${condition}/${sample}/FASTQ/singleReadsFASTQ.fastq \
                  --bam ${params.resultsDir}/${condition}/${sample}/transcriptomeAlignment/minimap.filt.sort.bam \
                  --genome transcriptome.fa --samples --signal-index --scale-events \
                  --rna --print-read-names --summary ${params.resultsDir}/${condition}/${sample}/f5c/transcriptome/summary.txt \
                  --slow5 ${params.resultsDir}/${condition}/${sample}/BLOW5/mergedBLOW5/merged.blow5 \
                  --threads ${task.cpus} > ${params.resultsDir}/${condition}/${sample}/f5c/transcriptome/eventalign_readName.txt

		f5c_x86_64_linux eventalign --reads ${params.resultsDir}/${condition}/${sample}/FASTQ/singleReadsFASTQ.fastq \
                  --bam ${params.resultsDir}/${condition}/${sample}/transcriptomeAlignment/minimap.filt.sort.bam \
                  --genome transcriptome.fa --signal-index --scale-events \
                  --rna --summary ${params.resultsDir}/${condition}/${sample}/f5c/transcriptome/summary.txt \
                  --slow5 ${params.resultsDir}/${condition}/${sample}/BLOW5/mergedBLOW5/merged.blow5 \
                  --threads ${task.cpus} > ${params.resultsDir}/${condition}/${sample}/f5c/transcriptome/eventalign_readIndex.txt

	"""
	else
	"""
        echo "Skipped"
    """
}`

The output file sizes are as follows.

f5c:

![image](https://github.com/user-attachments/assets/e77a2612-0e78-4d21-a159-6f69dce9aa2f)

Nanopolish:
![image](https://github.com/user-attachments/assets/b66a1d27-201c-40c7-a6d5-c7c124ea1af1)

And the heads of the related eventalign_readName files which I use for most of my m6a-callers:

f5c:
![image](https://github.com/user-attachments/assets/1c00bae1-5a36-4c3c-a34b-aa733f7a1671)

nanopolish:

![image](https://github.com/user-attachments/assets/f460e3d9-55ba-470f-88c4-68756b2edf52)

Also, the tools that I use which are not reliant on f5c seem to have the same performance as before, so I don't think that I made a mistake converting from fast5 to pod5 or mapping/getting the fastq. I am using a merged blow5 file instead of a series of fast5 directories, and am also providing the fastq from guppy outright instead of extracting it with poretools from each single fast5 file like had been done in the prior pipeline run. 

I would greatly appreciaite any help on the matter, and am happy to provide any additional context!

**Comment by hasindu2008** [comment]
Hello,

At the end of the run, both nanopolish and f5c should print some stats to the stderr that state the number of aligned reads, skipped reads, etc. This file size difference is likely to be due to differences in the default MAPQ cut-off and/or secondary alignments. 

You can pass `--min-mapq 0` to not filter out any low mapq reads and `--secondary=yes` to f5c to process secondary alignments. I reckon it would be this `--min-mapq 0`, because in direct RNA many reads have MAPQ 0, unlike in DNA. Adding secondary alignments would not make much sense.


Also, while not relevant to this issue, rather than fast5->pod5->blow5, you can directly go to fast5->blow5 using slow5tools if you wish.

**Comment by BrendanBeahan** [comment]
Perfect thank you very much! I will re-test using the differences in mapping quality threshold. And yes, the pipeline is currently only really designed with RNA004 pod5 input in mind, so the conversion from fast5 to pod5 is essentially a one-off. But indeed, I could integrate that more difrect fast5 -> blow5 process to make it more generalizable. 

I will report back after running the updated flag!

**Comment by BrendanBeahan** [comment]
It was indeed the flag --min-mapq 0, the output is identical now. Thanks again!
