### ISSUE TITLE
f5c index error kseq_read

### ISSUE THREAD

**Issue by SamuelErnestRoss** [hasindu2008/f5c#188]
Hello,

I get the following error when trying to index files form a RNA004 run

```
f5c index --version

F5C 1.5

f5c index --slow5 PNXRHF240491_reads.blow5  PNXRHF240491_pass_hac.fastq

[index_main] Slow5 index built - took 871.945s

kseq_read returned -2 indicating an error with the input file PNXRHF240491_pass_hac.fastq

```

I then do not get any  index.fai output

I have not had any other problems with these files, and have been able to map them as normal etc

**Comment by hasindu2008** [comment]
kseq_read -2 means a truncated quality string. May I suggest you to run `samtools fqidx PNXRHF240491_pass_hac.fastq` command and see if it gives any errors?

**Comment by SamuelErnestRoss** [comment]
samtools fqidx revealed i was missing the final line and quality information for the last read in all my fastq files. Not sure how that happened. Removing the last read from the files solved all other issues.

Cheers
