### ISSUE TITLE
About the support for pod5

### ISSUE THREAD

**Issue by JeremyQuo** [hasindu2008/f5c#190]
Will f5c add the support for pod5 in the future?

**Comment by Psy-Fer** [comment]
Hey,

I'm the maintainer of blue-crab which lets you convert pod5<->S/Blow5 files in a lossless way.

As hasindu mentioned, this allows developers to use the slow5 format, which is pretty simple and easy to use and has a number of advantages over pod5. 

Here is a link to the repo

https://github.com/Psy-Fer/blue-crab


Or you can install it from pip with 

`pip install blue-crab`

Cheers,
James

**Comment by JeremyQuo** [comment]
Many thanks. Gotta it.
