### ISSUE TITLE
[handle_bad_fast5::WARNING] Fast5 file [] for read [xxx] is unreadable and will be skipped

### ISSUE THREAD

**Issue by billytcl** [hasindu2008/f5c#51]
I'm running f5c on some nanopore minION 9.4.1 data, basecalled with guppy v3.2.1.

It's currently running fine with nanopolish but a little slow, so I wanted to check out f5c.

Commands ran (similar to nanopolish):
nice ~/f5c-v0.2-beta/f5c_x86_64_linux_cuda index -v -s ../00_fastq/sequencing_summary.txt -d ../00_fastq/workspace/ merged.fastq &
nice ~/f5c-v0.2-beta/f5c_x86_64_linux_cuda call-methylation -t 40 -g /mnt/ix1/Resources/GenomeRef/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa -b ../01_minimap2/PBMC_nucleosome.sorted.bam -r merged.fastq > PBMC.methylation.tsv &

I suddenly started getting spammed with the following:

[handle_bad_fast5::WARNING] Fast5 file [] for read [7e378c24-b327-4614-8177-1f5e87c9a6a3] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [164eaab1-e365-4c1f-847c-c2fdf138c261] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [cad224f4-c271-4223-96b4-f5c08dbaeb7c] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [2d4b2390-f8b6-4bc0-a651-6ddaa52f9821] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [e15dd481-2835-4d3e-8886-76b785ae252f] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [4423ba53-5e63-4ee6-a459-b81e7c8abcca] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [47d56611-9448-4d38-913b-c1213b4bcb2c] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [ea23a44d-3c3e-42bb-b701-6ef88d4ff492] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [3a01a4b1-1d17-4adc-ac49-49442920a5ca] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [f5733f05-693d-45fe-8669-c1b5c8daf822] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [91501677-34e9-4eba-8f37-be9178981065] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [4b549791-217b-40f1-aedc-ec7f9e27cdb8] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [54e53420-00b9-4c5c-b843-3c390f43a0f7] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [d65ce225-704e-4d8d-92df-6438fc54eaa5] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [33e2839a-c7b7-4d64-912c-2fcddae425d7] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [285512ab-9f9a-4358-b346-4e8fa4cc4aa3] is unreadable and will be skipped
[handle_bad_fast5::WARNING] Fast5 file [] for read [71ce87bb-f1fe-4115-b11d-f44f3f3385eb] is unreadable and will be skipped

I'm guessing the index wasn't properly built? Not sure how to fix this.

**Comment by hasindu2008** [comment]
As you guessed I also think that the index was not built properly.

1. Do you have the log from the index command?
For instance the part which says the number of reads and the reads with the
path.

[readdb] num reads: 112, num reads with path to fast5: 112

2. Is your dataset composed of single fast5 or multi fast5? Only recently I
included support for multi fast5 and is only available in the github dev
branch (still did not cut a release).

**Comment by billytcl** [comment]
It looks like they are multi fast5s. I cloned the latest version of f5c from the dev branch; verified here:

billylau@iwashi:~/f5c$ cat .git/config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/hasindu2008/f5c
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "dev"]
        remote = origin
        merge = refs/heads/dev

I am am getting this error after indexing with ~/f5c/f5c index -v -s ../00_fastq/sequencing_summary.txt -d ../00_fastq/workspace/ merged.fastq &:

[readdb] indexing ../00_fastq/workspace/
[readdb] num reads: 22184316, num reads with path to fast5: 5547

[main] CMD: /home/billylau/f5c/f5c index -v -s ../00_fastq/sequencing_summary.txt -d ../00_fastq/workspace/ merged.fastq
[main] Real time: 699.787 sec; CPU time: 692.300 sec; Peak RAM: 5.728 GB

**Comment by hasindu2008** [comment]
Is the above output from the updated version of f5c?

Still something seems to be wrong, as only for a fraction of reads that it has found the path. I can think of a couple of reasons.

1. Fast5 are not existent. Did you verify if the location ../00_fastq/workspace contain the expected fast5 files for all the reads in the fastq file? 

2. The sequencing summary format has changed. You can try indexing without -s option, but this will be too slow.

If you can share the first few lines of the .readbb file generated by the index and the first few lines in the sequencing summary, I can have a look.

**Comment by billytcl** [comment]
I double checked the folder and there are the correct number of fast5s inside.

I'm running without -s as a separate trial, but in the meantime here are the first few lines of readdb and the sequencing summary. It looks like they're not in the same order? In nanopolish this is working, BTW:

00000056-709d-45be-8ef0-fcb1e7bcaa38
0000009a-53eb-414d-bd3b-a30553f95d28
000000df-3de0-4894-9fec-40c007d76f60
0000014b-dab5-4bd0-a34d-52cdcd263254
000002ea-0f99-4e50-b49f-bcf08cbe5f81
00000302-0c65-4cc0-bb89-6b55017899de
000003a9-d557-43e7-8ff7-5220ae8f3a2c
00000444-815b-4d6a-a964-1e8ed7618cc9
00000470-d6da-4aaa-902d-26c97b722eff
000004fc-1e3b-4d7b-b1d7-c05618fad4a5
000005cd-91f5-4a12-81f9-afcae8599f2e
00000618-ec69-47e0-94fc-2b29bf43f08d
00000661-aba0-411c-8fbb-b44eeb35683c
00000695-2a9a-470a-a3e3-1338d36e0e34
00000695-a146-4d71-82d5-f7fd8cffebfe
0000074d-0278-4402-b648-0ca10f8897bb
00000762-bb41-4877-8497-22b37c24d4d2
0000087d-695b-4f26-ba36-b9284b9382a0
00000a13-997e-430d-9065-5e5ccd2eb86d
00000a6a-3180-46b2-9a7b-940d9f244fca

filename        read_id run_id  batch_id        channel mux     start_time      duration        num_events      passes_filtering        template_start  num_events_template     template_duration       sequence_length_template        mean_qscore_template   strand_score_template   median_template mad_template
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    97b6637a-56b4-434b-8758-b86a86fc7121    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       446     3       71148.468750    0.700500        1401    TRUE    71148.531250    1284  0.642000 183     11.357487       0.000000        82.585480       8.416355
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    6432cea2-36c3-4564-bcc8-afe89a651340    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       293     1       71150.726562    0.839250        1678    TRUE    71150.992188    1149  0.574750 190     9.048741        0.000000        83.988205       9.293058
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    90c686ae-4832-4860-8758-3c4c1a0a5a8a    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       249     3       71149.671875    1.205000        2410    TRUE    71149.812500    2123  1.061500 296     11.143431       0.000000        91.703201       9.819080
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    ac4fe456-b2f2-41f0-b1fd-d9277e525681    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       35      1       71141.203125    0.846750        1693    TRUE    71141.453125    1191  0.595750 194     12.241491       0.000000        82.585480       9.819080
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    e0eaa9ff-f495-4521-a984-adf48bf1f4f0    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       137     4       71151.718750    0.938000        1876    FALSE   71151.757812    1786  0.893000 323     5.856732        0.000000        70.486969       9.994421
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    0d8f8508-c817-4cca-a2c8-06da3a108703    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       399     1       71139.296875    0.986000        1972    TRUE    71139.414062    1735  0.867500 273     12.338060       0.000000        88.371727       9.819080
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    2d6c4d20-0275-442f-9532-6888ed470f50    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       289     1       71140.406250    0.620250        1240    TRUE    71140.445312    1157  0.578750 174     12.992059       0.000000        86.793663       10.169763
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    e7386156-35d9-4f56-aa40-0f9e3f88f468    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       375     2       71151.929688    0.655250        1310    TRUE    71151.945312    1272  0.636250 188     10.343980       0.000000        78.026627       9.117718
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    d9ac7787-50d2-4c19-b211-c6026abe8ac5    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       106     1       71152.773438    1.370000        2740    TRUE    71152.820312    2635  1.317500 349     12.267226       0.000000        91.527863       9.994421
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    7e094b41-4133-48cd-87a0-908308548c01    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       75      2       71151.875000    1.381000        2762    TRUE    71152.023438    2464  1.232000 317     10.085772       0.000000        86.618317       8.942377
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    d81a98a3-1362-46da-a0b7-1b464ad70cdd    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       280     3       71145.062500    0.856250        1712    TRUE    71145.296875    1246  0.623250 152     11.761046       0.000000        68.908905       8.065674
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    828eac5f-9db2-4ceb-9ada-8bf0e16a7bb6    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       228     1       71146.546875    0.683750        1367    TRUE    71146.625000    1212  0.606250 209     9.582952        0.000000        91.352516       10.695785
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    3c12a7c5-b616-45a4-b18e-ecd3e5559660    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       165     3       71155.140625    0.625750        1251    TRUE    71155.226562    1090  0.545250 199     12.355986       0.000000        82.234802       9.643740
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    7df38ed0-f7ed-4eca-aeb2-eb8057f439d3    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       241     2       71145.976562    1.090750        2181    TRUE    71146.296875    1536  0.768250 280     8.673992        0.000000        84.338890       10.871125
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    2b20c179-dee5-4f51-a0d4-a5bd6e6950c2    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       207     3       71149.304688    1.000000        2000    FALSE   71149.328125    1963  0.981500 184     6.251022        0.000000        79.429352       7.714992
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    27008ae9-847e-4ca5-bfa6-7f80a55d63a6    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       404     1       71148.445312    0.787000        1574    TRUE    71148.570312    1323  0.661500 207     10.502707       0.000000        78.377304       9.819080
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    28b791ab-b132-4bf7-be69-2dc8c759b387    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       447     4       71153.703125    0.726750        1453    TRUE    71153.789062    1274  0.637250 200     12.828352       0.000000        73.292427       8.241014
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    715686b1-6658-4b23-9bee-78905e24d80a    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       215     3       71146.921875    0.891500        1783    FALSE   71146.929688    1779  0.889500 190     5.468069        0.000000        84.864914       5.610903
FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1894.fast5    8e4b3227-30f6-4b9c-9118-67de863b9921    36c8477dbfb44575c0d1cc063920d2dea85e131c        0       167     2       71142.875000    0.632500        1265    TRUE    71142.898438    1211  0.605500 194     7.986514        0.000000        77.851280       9.468399

**Comment by billytcl** [comment]
Actually, it looks like the order doesn't matter, but this is the nanopolish output:

00000056-709d-45be-8ef0-fcb1e7bcaa38    ../00_fastq/workspace//FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_1006.fast5
0000009a-53eb-414d-bd3b-a30553f95d28    ../00_fastq/workspace//FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_740.fast5
000000df-3de0-4894-9fec-40c007d76f60    ../00_fastq/workspace//FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_3748.fast5
0000014b-dab5-4bd0-a34d-52cdcd263254    ../00_fastq/workspace//FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_701.fast5
000002ea-0f99-4e50-b49f-bcf08cbe5f81    ../00_fastq/workspace//FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_873.fast5
00000302-0c65-4cc0-bb89-6b55017899de    ../00_fastq/workspace//FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_3879.fast5
000003a9-d557-43e7-8ff7-5220ae8f3a2c    ../00_fastq/workspace//FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_602.fast5
00000444-815b-4d6a-a964-1e8ed7618cc9    ../00_fastq/workspace//FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_4371.fast5
00000470-d6da-4aaa-902d-26c97b722eff    ../00_fastq/workspace//FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_3747.fast5
000004fc-1e3b-4d7b-b1d7-c05618fad4a5    ../00_fastq/workspace//FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_2934.fast5

**Comment by hasindu2008** [comment]
Thanks for the information. Let me know how the index without the summary go. Probably some columns in the sequencing summary has changed. I will check sequencing summary from that particular version of guppy soon.

**Comment by hasindu2008** [comment]
@billytcl Thanks for picking up the issue. I fixed it in the latest dev branch. Check it out at https://github.com/hasindu2008/f5c/tree/dev and let me know.

**Comment by hasindu2008** [comment]
I have closed this issue as the bug is fixed in the test f5c 0.3 release. If still it causes issues please reopen the issue. 1

**Comment by senukobla** [comment]
I am getting the same error - what is the solution

**Comment by hasindu2008** [comment]
Hello @senukobla 
Could you please provide a bit more information about the data you are using, the command line parameters you are invoking and the log messages before and after the error? As this thread is very old, I suggest opening a new issue.

**Comment by jambler24** [comment]
Hi, also experiencing the same issue. Running on v1.3 from Conda. 

Command run:
```
f5c call-methylation -t 8 -r default_id.merged.fastq.gz  -b default_id_merged.sorted.bam  -g genome.fa > default_id_methylation_calls.tsv

```

Log snippet:

```
[meth_main::INFO][1;34m Default methylation tsv output format is changed from f5c v0.7 onwards to match latest nanopolish output. Set --meth-out-version=1 to fall back to the old format.[0m
[init_core::INFO][1;34m builtin DNA R9 nucleotide model loaded[0m
[init_core::INFO][1;34m builtin DNA R9 cpg model loaded[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [95777029-a957-4231-8668-fba26b9657b5] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [8c452463-0146-5cac-928d-2090b40ce84b] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [4b9eabfa-2b85-5b07-aaf4-dd3a42fa3162] is unreadable and will be skipped[0m
[meth_main::0.675*1.01] 512 Entries (0.2M bases) loaded
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [5cf16c24-d1f4-587f-8aa1-95bfb1e350b4] is unreadable and will be skipped[0m
[pthread_processor::0.962*2.99] 512 Entries (0.2M bases) processed
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [d1092f86-842c-5dd8-8f5c-027e66282f33] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [9bf407d7-1ccc-5228-96f7-5932a9a3dc56] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [9fbb650b-c93c-56de-927f-85725ed987cd] is unreadable and will be skipped[0m
[meth_main::1.283*2.50] 512 Entries (0.2M bases) loaded
[slow_fast5_warn::INFO][1;34m Fast5 reading took more time than processing. Try increasing --iop. See http://bit.ly/f5cperf[0m
[pthread_processor::1.499*3.40] 512 Entries (0.2M bases) processed
[meth_main::1.887*2.91] 512 Entries (0.2M bases) loaded
[slow_fast5_warn::INFO][1;34m Fast5 reading took more time than processing. Try increasing --iop. See http://bit.ly/f5cperf[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [ed1c51dd-736f-5f66-a562-34132ee09aa3] is unreadable and will be skipped[0m
[pthread_processor::2.106*3.52] 512 Entries (0.2M bases) processed
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [4842bb36-7bca-5a75-8473-271ef3277379] is unreadable and will be skipped[0m
[meth_main::2.489*3.14] 512 Entries (0.2M bases) loaded
[slow_fast5_warn::INFO][1;34m Fast5 reading took more time than processing. Try increasing --iop. See http://bit.ly/f5cperf[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [97591ae0-b3c1-5efb-a0a0-819833a7a669] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [9f4d86b7-0ef2-5e05-b51c-127706cd3908] is unreadable and will be skipped[0m
[pthread_processor::2.708*3.60] 512 Entries (0.2M bases) processed
[meth_main::3.092*3.28] 512 Entries (0.2M bases) loaded
[slow_fast5_warn::INFO][1;34m Fast5 reading took more time than processing. Try increasing --iop. See http://bit.ly/f5cperf[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [304e7e6d-e2fa-5bef-baf3-d4525f355e0b] is unreadable and will be skipped[0m
[pthread_processor::3.307*3.64] 512 Entries (0.2M bases) processed
[meth_main::3.696*3.37] 512 Entries (0.2M bases) loaded
[slow_fast5_warn::INFO][1;34m Fast5 reading took more time than processing. Try increasing --iop. See http://bit.ly/f5cperf[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [2bdab071-9937-516d-8752-2e8ccd1337b8] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [37370995-e313-52af-ae32-d49db372e35f] is unreadable and will be skipped[0m
[pthread_processor::3.923*3.69] 512 Entries (0.2M bases) processed
[meth_main::4.305*3.45] 512 Entries (0.2M bases) loaded
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [fc8954ec-be53-5ea3-8ead-103b28687813] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [c55fc93f-dd27-55a0-bb97-49fc1bdc121f] is unreadable and will be skipped[0m
[pthread_processor::4.608*3.70] 512 Entries (0.2M bases) processed
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [793b5b5c-3489-5b63-aa9d-7350abfc9b84] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [1a87f65e-654a-539b-a46d-c887d80a2e41] is unreadable and will be skipped[0m
[meth_main::4.917*3.53] 512 Entries (0.2M bases) loaded
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [f86c3eb5-c52c-5c9f-9eb6-07246f70b16c] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [c4ad5ac4-e6ee-5e16-b48d-7becd0bb0257] is unreadable and will be skipped[0m
[pthread_processor::5.148*3.77] 512 Entries (0.2M bases) processed
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [8f941c71-f748-553f-b3da-f067e15aee45] is unreadable and will be skipped[0m
[meth_main::5.524*3.58] 512 Entries (0.2M bases) loaded
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [a54f2f34-d75f-5873-b6f5-4be92d504ee0] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [3b197b66-e861-5a64-8e79-a089895eb612] is unreadable and will be skipped[0m
[pthread_processor::5.744*3.79] 512 Entries (0.2M bases) processed
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [b503680b-9c21-53fd-8ff2-24f3583f96b3] is unreadable and will be skipped[0m
[meth_main::6.131*3.61] 512 Entries (0.2M bases) loaded
[pthread_processor::6.351*3.79] 512 Entries (0.2M bases) processed
[meth_main::6.737*3.63] 512 Entries (0.2M bases) loaded
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [92894585-4a1e-507a-8218-317a5c2a716f] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [0fa48c44-5beb-545e-9177-fddf5680c0e5] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [69881832-0c7f-5225-9564-598862b1dd81] is unreadable and will be skipped[0m
[pthread_processor::7.037*3.80] 512 Entries (0.2M bases) processed
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [fd048fd9-6f59-56db-95f6-fa699847c23b] is unreadable and will be skipped[0m
[meth_main::7.347*3.68] 512 Entries (0.2M bases) loaded
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [8bcd955e-9db5-53e4-9bc3-bd3d723449a1] is unreadable and will be skipped[0m
[pthread_processor::7.570*3.84] 512 Entries (0.2M bases) processed
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [710a19a1-aa23-4ef2-813f-6cd778b6ef34] is unreadable and will be skipped[0m
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [fa4e1acd-1040-5a1c-a9e4-9599bee28aa9] is unreadable and will be skipped[0m
[meth_main::7.955*3.70] 512 Entries (0.2M bases) loaded

...

[pthread_processor::38.837*4.03] 512 Entries (0.5M bases) processed
[meth_main::38.905*4.02] 512 Entries (0.6M bases) loaded
[handle_bad_fast5::WARNING][1;33m Fast5 file [] for read [593248a1-be18-5dae-beeb-c5c33f6ea056] is unreadable and will be skipped[0m
[meth_main::39.083*4.05] 143 Entries (0.1M bases) loaded
[pthread_processor::39.455*4.08] 512 Entries (0.6M bases) processed
[pthread_processor::39.527*4.09] 143 Entries (0.1M bases) processed
[meth_main] skipped unmapped: 0, skipped secondary: 0, skipped low_mapq: 4004
[meth_main] total entries: 32647, qc fail: 0, could not calibrate: 0, no alignment: 32399, bad reads: 248
[meth_main] total bases: 15.3 Mbases
[meth_main] Data loading time: 38.983 sec
[meth_main]     - bam load time: 0.338 sec
[meth_main]     - fasta load time: 19.216 sec
[meth_main]     - fast5 load time: 19.141 sec
[meth_main]         - fast5 open time: 5.712 sec
[meth_main]         - fast5 read time: 12.033 sec
[meth_main] Data processing time: 16.541 sec
[meth_main] Data output time: 0.000 sec
[meth_main::INFO][1;34m Performance bounded by file I/O. File I/O took 22.441 sec than processing[0m
[meth_main::WARNING][1;33m 32399 out of 32647 reads failed. Double check --pore and --rna options.[0m
[main] Version: 1.3
[main] CMD: f5c call-methylation -t 8 -r default_id.merged.fastq.gz -b default_id_merged.sorted.bam -g genome.fa
[main] Real time: 39.535 sec; CPU time: 161.501 sec; Peak RAM: 0.591 GB

ls: cannot access '*.log': No such file or directory

```

**Comment by hasindu2008** [comment]
Hey @jambler24 
Your issue seems to be something different majority of the reads have failed alignment. Is this newer r10 data?

**Comment by jambler24** [comment]
Hi @hasindu2008 ! 

Yup seems like the unreadable reads error was a red herring, and the answer was in the last lines of the log.

`[meth_main::WARNING]�[1;33m 32399 out of 32647 reads failed. Double check --pore and --rna options.�[0m
`
 I was using R10.4 data (facepalm)

Fix was adding the `--pore "r10"` flag. 

Leaving this here in case anyone else missed that!

**Comment by hasindu2008** [comment]
Glad it got the issue fixed. If you are using BLOW5 as the input (which the fast5 can be converted using https://github.com/hasindu2008/slow5tools and pod5 using https://github.com/Psy-Fer/blue-crab), these pore-related metadata will be automatically detected. In addition, it will be much faster too. The reason I haven't been able to do the autodetect for FAST5 is that FAST5 keeps on changing and there are dozens of inconsistencies that are time consuming to handle. You can ignore the "is unreadable and will be skipped" warning, because, looking at the summary stats, only 248 out of 32647 reads have caused this, which is very likely to be due to this new "read splitting" feature in the latest basecallers, that splits some reads and creates new read ids, which then f5c cannot find in the FAST5.
