### ISSUE TITLE
HDF5 error when running

### ISSUE THREAD

**Issue by vahidAK** [hasindu2008/f5c#55]
Hi @hasindu2008 
I installed f5c without error but when I run it, it gives me this error:

[init_cuda] Running on Tesla V100-SXM2-32GB (device id 3)
[cuda_freemem] 19.77 GB free of total 31.72 GB GPU memory
[init_cuda] Max GPU capacity 11.8M bases
[init_cuda::INFO] Your GPU can accommodate upto 11.8M bases. You may increase -B option (currently 0.0M) for better performance!
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140452057438016:
  #000: ../../../src/H5L.c line 1117 in H5Lget_name_by_idx(): name doesn't exist
    major: Symbol table
    minor: Object already exists
  #001: ../../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #002: ../../../src/H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
    major: Symbol table
    minor: Object not found
[fast5_read::WARNING] Failed to retrieve the size of the read name.
[handle_bad_fast5::WARNING] Fast5 file [/projects/vakbari_prj/scratch/NA12878_fast5s//PLSP57501_20161028_FNFAB42451_MN16458_sequencing_run_Nott_Hum_R9_4_3_0.fast5] for read [3b450dea-7ad4-42b0-8ab1-acb8f8438f56] is unreadable and wi
ll be skipped
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140452057438016:
  #000: ../../../src/H5L.c line 1117 in H5Lget_name_by_idx(): name doesn't exist
    major: Symbol table
    minor: Object already exists
  #001: ../../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #002: ../../../src/H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
    major: Symbol table
    minor: Object not found
[fast5_read::WARNING] Failed to retrieve the size of the read name.
[handle_bad_fast5::WARNING] Fast5 file [/projects/vakbari_prj/scratch/NA12878_fast5s//makeson_PC_20161117_FNFAB44989_MN17284_sequencing_run_MA_470_R9_4_NA12878_11_17_16_115.fast5] for read [a2227fb3-191a-49b7-a6c4-f1d8224aeabd] is u
nreadable and will be skipped

Can you please help me in this matter?

Thanks,
Vahid.

**Comment by hasindu2008** [comment]
Hi,

Can I know the following?
1. if these are multi-fast5 or single-fast5? If multi-fast5 could you please try the latest [dev](https://github.com/hasindu2008/f5c/tree/dev) branch.  Multi-fast5 support was very recently added and I still did not make a release version?
2. are seeing this message just for a single read or the majority of the reads?

**Comment by vahidAK** [comment]
Hi @hasindu2008,  
My files are multi-read fast5s. I installed the latest f5c version v0.2 beta.
I see this message as soon as I run the program. It seems I am getting this error at reading first fast5 file.
Thanks,
Vahid.

**Comment by hasindu2008** [comment]
That particular release version does not have fast5 support integrated. I am planning to do a release that includes multi-fast5 soon, after doing a couple of tests. Meanwhile, could you check the development version that I am attaching herewith. You can compile it the same way you did for version v0.2 beta. Let me know if it works on your multi-fast5s.
[f5c-v0.2-beta-10-g8e0bae0-release.tar.gz](https://github.com/hasindu2008/f5c/files/3797076/f5c-v0.2-beta-10-g8e0bae0-release.tar.gz)

**Comment by vahidAK** [comment]
Sure, I'll try and let you know

**Comment by vahidAK** [comment]
Hi @hasindu2008 
it works, but I see this massage and it seems it does not use GPU:
[load_balance_advisor::INFO] GPU got too much work. Try increasing --ultra-thresh, decreasing --cuda-max-lf, decre      asing --cuda-max-epk. Else, CPU is too powerful than GPU and just ignore. See http://bit.ly/f5cperf                     [memory_balance_advisor::INFO] GPU arrays under-utilised. Try increasing -B. See http://bit.ly/f5cperf                  [process_db::21.529*0.95] Banded alignment done                                                                         [process_db::21.537*0.95] Scaling calibration done                                                                      [process_db::21.540*0.95] HMM done                                                                                      [pthread_processor::21.540*0.95] 1 Entries (0.2M bases) processed                                                       [process_db::21.569*0.95] Events computed                                                                               [meth_main::21.578*0.95] 1 Entries (0.0M bases) loaded                                                                  [align_cuda] Load : CPU 0 entries (0.0M bases), GPU 1 entries (0.0M bases)                                              [load_balance] Processing time : CPU 0.0 sec, GPU 0.1 sec                                                               [load_balance_advisor::INFO] GPU got too much work. Try increasing --ultra-thresh, decreasing --cuda-max-lf, decre      asing --cuda-max-epk. Else, CPU is too powerful than GPU and just ignore. See http://bit.ly/f5cperf                     [memory_balance_advisor::INFO] GPU arrays under-utilised. Try increasing -B. See http://bit.ly/f5cperf                  [process_db::21.714*0.95] Banded alignment done                                                                         [process_db::21.717*0.95] Scaling calibration done                                                                      [process_db::21.721*0.95] HMM done                                                                                      [pthread_processor::21.721*0.95] 1 Entries (0.0M bases) processed                                                       [process_db::21.745*0.95] Events computed                                                                               [meth_main::21.769*0.95] 1 Entries (0.0M bases) loaded                                                                  [align_cuda] Load : CPU 0 entries (0.0M bases), GPU 1 entries (0.0M bases)                                              [load_balance] Processing time : CPU 0.0 sec, GPU 0.2 sec                                                               [load_balance_advisor::INFO] GPU got too much work. Try increasing --ultra-thresh, decreasing --cuda-max-lf, decre      asing --cuda-max-epk. Else, CPU is too powerful than GPU and just ignore. See http://bit.ly/f5cperf


Here is my command:
~/Software/f5c_newDev/f5c-v0.2-beta-10-g8e0bae0/f5c call-methylation -t 128 --cuda-dev-id 3 -B 10.0 -r merged_guppy.fastq -b merged_guppy.sorted.bam -g Human_RG/hg38.fa > methy_calls.tsv

**Comment by hasindu2008** [comment]
Possibly you wanted **-B 10M** where you missed the M. Otherwise it will try to load 10 bases at a time and GPU will not have enough work to do - will be so slow. 

By the way, is it a Tesla V100 you have? In that case, 10M is a good value.

This version has been tested on small datasets and gives a similar answer to Nanopolish. I have not yet tested on massive datasets, but it should work and so the answer is reliable.

**Comment by vahidAK** [comment]
Thanks, @hasindu2008 
Yes, it is Tesla V100-SXM2.

**Comment by hasindu2008** [comment]
_Yes, it is Tesla V100-SXM2._

Great. If it is Tesla V100 increase the batch size by appending -K 1024 as follows and let me know how it goes.
`~/Software/f5c_newDev/f5c-v0.2-beta-10-g8e0bae0/f5c call-methylation -t 128 --cuda-dev-id 3 -B 10.0M -K 1024 -r merged_guppy.fastq -b merged_guppy.sorted.bam -g Human_RG/hg38.fa > methy_calls.tsv`

 _I was wondering is it possible to assign more than one GPU? something like: --cuda-dev-id 3 4 5_
Unfortunately, this version cannot use multiple GPUs simultaneously. In fact, you will realise that even with a single Tesla V100, a limitation in HDF5 library becomes the bottleneck and thus using multi GPUs under the same process is superfluous. However, you can manually call f5c on multiple samples separately (or on different partitions of the same sample if you have non concatenated  `fastqs`).

By the way, how large is your dataset and if your disk system NVMe?

**Comment by hasindu2008** [comment]
Hi @vahidAK 

Has this problem been solved? I have recent released f5c 0.3 with full multi fast5 support and a new --iop option for reading HDF5 files faster.
