### ISSUE TITLE
Is it possible to use multiple GPUs?

### ISSUE THREAD

**Issue by Shians** [hasindu2008/f5c#57]
It's not clear from 

```
--cuda-dev-id INT          CUDA device ID to run kernels on [0]
```

if multiple GPU can be used.

**Comment by hasindu2008** [comment]
multi GPU support for a single f5c instance is not yet implemented. This option is useful to specify which GPU should be used by f5c, incase there are multiple GPUs. I will clarify this, thanks for pointing out. 


At the moment, if you have multiple GPUs, you can call multiple f5c  instances manually, each f5c instance assigned to a particular GPU. This is useful when you want to process multiple datasets in parallel.

If still not clear let me know.

**Comment by LynnLy** [comment]
Hi Hasindu,

I'm trying to use two GPUs across two f5c calls, but I'm not sure if it is working. I used the precompiled binary v0.3-beta from the quickstart instructions.

Command 1: `./f5c_x86_64_linux_cuda call-methylation --cuda-dev-id 0 -B 4.0M -K 800 --iop 5 --cuda-mem-frac 0.3 -b {input.bam} -g {input.genome} -r {input.reads} -o {output}`  
Command 2: `./f5c_x86_64_linux_cuda call-methylation --cuda-dev-id 1 -B 4.0M -K 800 --iop 5 --cuda-mem-frac 0.3 -b {input.bam} -g {input.genome} -r {input.reads} -o {output}`

I can see in the output that it says 
`[init_cuda] Running on Quadro GV100 (device id 0)` and  
`[init_cuda] Running on Quadro GV100 (device id 1)` appropriately.

However, the nvidia-smi output seems to indicate that both processes are being run on device 0. 

`nvidia-smi` output:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro GV100        On   | 00000000:18:00.0 Off |                  Off |
| 33%   46C    P2    45W / 250W |  19672MiB / 32499MiB |     61%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro GV100        On   | 00000000:3B:00.0 Off |                  Off |
| 29%   34C    P2    25W / 250W |   5260MiB / 32499MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Quadro GV100        On   | 00000000:86:00.0 Off |                  Off |
| 29%   34C    P2    24W / 250W |   5260MiB / 32499MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Quadro GV100        On   | 00000000:AF:00.0 Off |                  Off |
| 29%   32C    P2    24W / 250W |   5260MiB / 32499MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4620      C   /usr/bin/guppy_basecall_server              5250MiB |
|    0     45563      C   ...gpu/f5c-v0.3-beta/f5c_x86_64_linux_cuda  8476MiB |
|    0     45885      C   ...gpu/f5c-v0.3-beta/f5c_x86_64_linux_cuda  5934MiB |
|    1      4620      C   /usr/bin/guppy_basecall_server              5250MiB |
|    2      4620      C   /usr/bin/guppy_basecall_server              5250MiB |
|    3      4620      C   /usr/bin/guppy_basecall_server              5250MiB |
+-----------------------------------------------------------------------------+
```

Is this the correct behavior and I am misinterpreting `nvidia-smi`, or is this a bug?

**Comment by hasindu2008** [comment]
@LynnLy 
In fact, it is a bug. Thanks for figuring it out. I have fixed the bug in the latest dev branch. Could you please check with attached binaries below and let me know.
[f5c-v0.3-beta-3-g0ce3b23-binaries.tar.gz](https://github.com/hasindu2008/f5c/files/3958756/f5c-v0.3-beta-3-g0ce3b23-binaries.tar.gz)

**Comment by LynnLy** [comment]
Fantastic, thanks for fixing that! It's working properly now.
