### ISSUE TITLE
Possible to specify a genomic interval?

### ISSUE THREAD

**Issue by andreaswallberg** [hasindu2008/f5c#58]
Dear @hasindu2008,

This software looks great! In Nanopolish, it is possible to specify an arbitrary genomic region/interval to scan using the "-w" flag, e.g.: -w ctg1:1-100000

Is it possible to accomplish something similar in f5c?

**Comment by hasindu2008** [comment]
That seems to be a newly introduced option in nanopolish or I missed it when writing f5c. I will soon implement this feature. Thanks for reporting.

**Comment by hasindu2008** [comment]
Hi @andreaswallberg 

I implemented the function of "-w" to f5c. You can get this feature in the latest commit of the dev branch or the compiled binaries attached below. Give it a try and let me know.

[f5c-v0.3-beta-4-ge02278d-binaries.tar.gz](https://github.com/hasindu2008/f5c/files/4044220/f5c-v0.3-beta-4-ge02278d-binaries.tar.gz)

**Comment by andreaswallberg** [comment]
Hi @hasindu2008 !

Sorry for the long delay. Thanks for implementing this! Just a quick question: can I specify more than one interval after a "-w" parameter, or pass several the "-w" parameter several times?

Cheers!

**Comment by hasindu2008** [comment]
At the moment such a feature to specify multiple regions is not yet implemented in f5c. Is such a feature available in Nanopolish?

**Comment by andreaswallberg** [comment]
Hi again!

We will look into what Nanopolish does.

My thinking is that it may help reduce overhead loading times if whatever general resources such as the genome sequence is read only once, after which the program can loop over many intervals, instead of having a bash loop to read everything over and over again.

**Comment by kpalin** [comment]
Many of the short command line options don't work and the documentation is outdated. But big thanks for the "--window" option and I looking forward for release of the "--meth-model" option

**Comment by hasindu2008** [comment]
Hi @kpalin 

Which f5c version are you using?

**Comment by kpalin** [comment]
v0.4 from Conda.

**Comment by hasindu2008** [comment]
@kpalin 
Could you update now to the latest version 0.5 (now available in conda as well)? The documentation is compatible with this version. If you find any options that are still not working/outdated please let me know.

--meth-model is available in this version as an experimental feature. Give it a try and let me know if you encounter an issue.

**Comment by hasindu2008** [comment]
I will close this issue for now but please reopen if you have more questions.
