### ISSUE TITLE
GPU mem needed ?

### ISSUE THREAD

**Issue by colindaven** [hasindu2008/f5c#59]
Hi,

I only have older low-mem GPUs available.

- GTX 950, 960, 
- 2GB GPU RAM
- 660 CUDA cores

Is it worth trying to compile and use the GPU version, or does the tool need something much bigger ?
Thanks,
Colin

**Comment by hasindu2008** [comment]
Hi,

f5c can run on such low memory GPUs when a smaller batch size (-K and -B options) is provided. What is the CPU of the particular systems?
If your system is Linux, you can quickly give a try using the compiled binaries as mentioned in the GitHub readme.

**Comment by colindaven** [comment]
Nice, thanks, we'll give it a crack. Yes, Linux, 4 core hyperthreaded on a workstation at present
```

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
stepping	: 3
microcode	: 0xd6
cpu MHz		: 800.094
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5424.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

```

**Comment by hasindu2008** [comment]
Have you succeeded in doing this?

**Comment by colindaven** [comment]
No, unfortunately the machine is too small with 32 GB RAM, limited network and 4 cores. We'll stick to the CPU version for practical reasons and build up a bigger GPU machine with better network.
Thanks for the hints though, very helpful.
