### ISSUE TITLE
Questions about running on linux server

### ISSUE THREAD

**Issue by jolespin** [hasindu2008/f5c#68]
I plan on running this program for A LOT of promthion runs.  I had a few questions:

* How is the performance for CPU vs. GPU? 
* Can GPU be utilized on this server? 
```
(base) -bash-4.1$ uname -r
2.6.32-754.23.1.el6.x86_64
```
* Is the GPU architecture configured for conda installations? 
* Does the number of threads scale linearly? For nanopolish it does not.

**Comment by hasindu2008** [comment]
How is the performance for CPU vs. GPU?
- The overall performance gain when I/O is included is around 2X.

Can GPU be utilized on this server?
- could you put the output of the command _nvidia-smi_ and `lspci -nnk | grep -iA2 "vga\|3d\|display"`? The GPU version requires an NVIDIA GPU and the NVIDIA driver installed.

Is the GPU architecture configured for _conda_ installations?
- Sadly no. The GPU version requires the NVIDIA C Compiler installed and I could not find a straight forward way to get this on Conda. Let me know if you have some experience with Conda in things like this.

Does the number of threads scale linearly? For nanopolish it does not.
- Yes. The _call-methylation_ module scales quite well well the number of threads. I usually run with 32 threads and get a PromethION sample done in around 10 hours. The multi-threaded performance is mainly affected by I/O, so make sure you place the FAST5 files in the local SSD scratch and use _--iop_ in addition to _-t_ option in f5c. Also, the batch size can be made larger for better performance with a large number of threads.

eg:  `f5c call-methylation-r reads.fastq -g ref.fa -b reads.bam -t 32 --iop 32 -K 2048 -B 20M`

**Comment by jolespin** [comment]
It looks like I don't have NVIDIA GPU available on our machine (as expected):

```
(base) -bash-4.1$ nvidia-smi
-bash: nvidia-smi: command not found
(base) -bash-4.1$ lspci -nnk | grep -iA2 "vga\|3d\|display"
00:02.0 VGA compatible controller [0300]: Device [1234:1111] (rev 02)
	Subsystem: Red Hat, Inc. Device [1af4:1100]
00:03.0 Ethernet controller [0200]: Red Hat, Inc. Virtio network device [1af4:1000]
```

 Should `--iop` always be the number of threads?

**Comment by hasindu2008** [comment]
An appropriate value for _iop_ depends on the disk system where the FAST5 files are placed. For fast SSD storage, 16 `iops `is enough. For HDD storage around 32 _iops_ works wells. However, if you are running from network storage (e.g., NFS, panfs) around 64 _iops_ are required. 

What type of storage do you have on the system that is large enough for a PromethION FAST5 dataset?

**Comment by jolespin** [comment]
Is there a command I can run to check what type of storage system is used on our server?

**Comment by hasindu2008** [comment]
Is it a cluster node or an independent server/workstation?

**Comment by hasindu2008** [comment]
I will close this issue for now but please reopen if you have more questions.
