### ISSUE TITLE
RNA model support

### ISSUE THREAD

**Issue by a-slide** [hasindu2008/f5c#73]
Hi @hasindu2008,

f5c eventalign throws the following error when trying to use the RNA model (r9.4_70bps.u_to_t_rna.5mer.template.model ):

```
[set_opt_profile] max-lf: 5.0, avg-epk: 2.0, max-epk: 5.0, K: 256, B: 1.5M, t: 4, ultra-thresh: 100.0k, iop: 1
[read_model::WARNING] Reading the model from file resources/r9.4_70bps.u_to_t_rna.5mer.template.model. This is an experimental feature. Use with caution
[read_model::ERROR] File resources/r9.4_70bps.u_to_t_rna.5mer.template.model is corrupted at line 0
[read_model::ERROR] File resources/r9.4_70bps.u_to_t_rna.5mer.template.model prematurely ended. Expected 4096 kmers in the model, but file had only 1025
```
Would you mind having a look ?

**Comment by hasindu2008** [comment]
Hi @a-slide 

At the moment, f5c does not support RNA alignment. I will soon check whether RNA alignment has significant differences to DNA alignment and let you know I can quickly port it.

**Comment by a-slide** [comment]
Great. Thanks @hasindu2008.
Would be nice to be able to switch our RNA mod pipeline to f5c.
Let me know if you need test datasets

**Comment by hasindu2008** [comment]
@a-slide 
A small dataset and commands used for typical nanopolish analysis would be very helpful.

**Comment by a-slide** [comment]
Thanks @hasindu2008 .
I will try to get you that. Do you want fast5 +  fastq + reference + nanopolish result ?

**Comment by hasindu2008** [comment]
@a-slide 
Yes. That would be ideal. 

In the meantime, I also downloaded some data from https://github.com/nanopore-wgs-consortium/NA12878/blob/master/RNA.md under the native RNA section and generated a potential test set using the following commands.

```
minimap2 -a -x map-ont  --secondary=no test/rna/gencode.v35.transcripts.fa test/rna/reads.fastq | samtools sort - > test/rna/reads.sorted.bam
nanopolish eventalign -b test/rna/reads.sorted.bam -g test/rna/gencode.v35.transcripts.fa -r test/rna/reads.fastq --summary test/rna/eventalign.summary.exp > test/rna/eventalign.exp
 ```
Are these commands and the reference used correct and representative of the RNA use-case you mentioned?

**Comment by a-slide** [comment]
Actually that might be a better dataset that what I had in mind, although it is a bit old now.
For the alignment I normally also filter out reads that are unmapped, secondary and supplementary as well as reads mapped on the reverse strand (mapping artefact if you use the transcriptome reference)

`minimap2 -ax map-ont transcriptome.fasta reads.fastq | samtools view -bh -F 2324 | samtools sort - > aligned_reads.bam`

The nanopolish command seems right

Thanks

**Comment by hasindu2008** [comment]
@a-slide 
RNA event align is now fully implemented in the [dev branch](https://github.com/hasindu2008/f5c/tree/dev). I tested using a small dataset (around 100 NA12878 direct RNA reads) and the results matched the ones from nanopolish. You can give a try as well.

I am doing some further testing using an in-house big RNA dataset and after that test, I will merge to the master branch and cut a release. f5c finished in 3 hours but nanopolish has been running for a few days now, hopefully, will finish soon.

**Comment by a-slide** [comment]
Good job @hasindu2008.
I will test with a larger dataset as soon as I can.
Thanks

**Comment by a-slide** [comment]
It seems to be working but on a larger Yeast dataset, I haven't done an extensive comparison with nanopolish.
In any cases it is fully downstream compatible with nanocompore.
Thanks

**Comment by hasindu2008** [comment]
I tried on a large mouse dataset and did some extensive comparison. Results are almost the same to nanopolish except for some tiny differences in floating-point numbers (mostly due to architectural differences).
Also, I have cut a release for version 0.6. Thank you very much for this suggestion and the help in testing.

I will close this issue for now but do not hesitate to open a new one for any issues or feature requests.
