### ISSUE TITLE
Support for --samples option in eventalign 

### ISSUE THREAD

**Issue by a-slide** [hasindu2008/f5c#74]
Hi @hasindu2008 

We use the `--samples` option in nanopolish eventalign to extract accurate signal parameters at kmer level in Nanocompore for RNA modification detection. It appears that the option is not yet available in fc5 eventalign. I know that it considerably increase the size of the file but we normally directly pipe into our pipeline.
 
Would you consider adding it ?

Thanks

**Comment by hasindu2008** [comment]
Yes, I would soon add this --samples option. Adding it to the existing DNA alignment is quite easy, I will investigate RNA alignment as I mentioned in the other response and let you know.

**Comment by a-slide** [comment]
Thanks

**Comment by hasindu2008** [comment]
@a-slide Now *f5c* [dev branch](https://github.com/hasindu2008/f5c/tree/dev) supports --samples for DNA eventalign and the output formatting is parallelised for much faster multi-threaded performance.

**Comment by a-slide** [comment]
I can confirm it works for both DNA and RNA
Thanks @hasindu2008 

By the way I pushed a singularity container with the dev version of f5 in case you are interested
containers: https://cloud.sylabs.io/library/aleg/default/f5c)
recipes: https://github.com/a-slide/singularity/tree/main/f5c

**Comment by hasindu2008** [comment]
@a-slide 
Thank you very much for testing and thanks for creating those singularity containers!
