### ISSUE TITLE
Installation on Jetson Xavier

### ISSUE THREAD

**Issue by PhiloVa** [hasindu2008/f5c#81]
Hello and thanks for your work!

This is an issue that I managed to solve (I hope correctly) for the compiling part on a Jetson Xavier AGX. I hope it helps anyone in the future.

So the makefile had an error 1 issue for the jetson on the nvcc command:
~/ssd/f5c$ make cuda=1 CUDA_ARCH=-arch=sm_72
nvcc -x cu -g  **-O2** -std=c++11 -lineinfo -arch=sm_72 -Xcompiler -Wall  -DNDEBUG -D_FORTIFY_SOURCE=2 **-O2** -isystem /home/magos/miniforge3/include -I./htslib -I./hdf5/include/   -DHAVE_CUDA=1 -rdc=true -c src/f5c.cu -o build/f5c_cuda.o
nvcc fatal   : redefinition of argument 'optimize'
Makefile:106: recipe for target 'build/f5c_cuda.o' failed
make: *** [build/f5c_cuda.o] Error 1

Looking into it, it seems nvcc doesn't like double commands. In this case, it was **-02**. So I removed it from line 37 of the makefile and it then ran smoothly.

BENCHMARKING:
Additionally and FYI, it seems the profile created for the Xavier underestimates the power of this little machine. In my benchmarking tests, the jetson-xavier profile batch_size_bases (-B) were boosted to 10M (from 4.7M) successfully.
Here are both results with original profile and -B 10000000:

1. jetson-xavier profile:
[meth_main] total entries: 155764, qc fail: 65, could not calibrate: 21, no alignment: 1563, bad fast5: 0
[meth_main] total bases: 1016.6 Mbases
[meth_main] Data loading time: 734.721 sec
[meth_main]     - bam load time: 24.476 sec
[meth_main]     - fasta load time: 237.770 sec
[meth_main]     - fast5 load time: 470.616 sec
[meth_main]         - fast5 open time: 1.209 sec
[meth_main]         - fast5 read time: 469.407 sec
[meth_main] Data processing time: 1668.647 sec
[meth_main]     - Events time: 187.296 sec
[meth_main]     - Alignment time: 340.338 sec
[meth_main]           -cpu preprocess time: 74.669 sec
[meth_main]           -cuda malloc time: 0.028 sec
[meth_main]           -cuda data transfer time: 68.465 sec
[meth_main]           -cuda kernel time: 90.964 sec
[meth_main]                -align-pre kernel only time: 5.213 sec
[meth_main]                -align-core kernel only time: 62.657 sec
[meth_main]                -align-post kernel only time: 23.095 sec
[meth_main]           -cpu postprocess time: 11.736 sec
[meth_main]           -additional cpu processing time (load imbalance): 94.422 sec
[meth_main]     - Estimate scaling time: 67.992 sec
[meth_main]     - HMM time: 1072.918 sec
[meth_main] Data output time: 52.714 sec
[main] Version: 0.6
[main] CMD: ./f5c call-methylation -t 8 -x jetson-xavier -r [FASTQ_PATH] -g [REF_GENOME_PATH] -b [BAM_PATH]
[main] Real time: 1693.154 sec; CPU time: 9019.244 sec; Peak RAM: 3.655 GB

2. jetson-xavier profile -B 10000000:
[meth_main] total entries: 155764, qc fail: 65, could not calibrate: 21, no alignment: 1563, bad fast5: 0
[meth_main] total bases: 1016.6 Mbases
[meth_main] Data loading time: 626.032 sec
[meth_main]     - bam load time: 20.327 sec
[meth_main]     - fasta load time: 199.510 sec
[meth_main]     - fast5 load time: 404.742 sec
[meth_main]         - fast5 open time: 0.771 sec
[meth_main]         - fast5 read time: 403.970 sec
[meth_main] Data processing time: 1326.607 sec
[meth_main]     - Events time: 153.801 sec
[meth_main]     - Alignment time: 292.182 sec
[meth_main]           -cpu preprocess time: 65.607 sec
[meth_main]           -cuda malloc time: 0.028 sec
[meth_main]           -cuda data transfer time: 57.686 sec
[meth_main]           -cuda kernel time: 81.498 sec
[meth_main]                -align-pre kernel only time: 4.325 sec
[meth_main]                -align-core kernel only time: 57.996 sec
[meth_main]                -align-post kernel only time: 19.177 sec
[meth_main]           -cpu postprocess time: 9.728 sec
[meth_main]           -additional cpu processing time (load imbalance): 77.610 sec
[meth_main]     - Estimate scaling time: 54.829 sec
[meth_main]     - HMM time: 825.747 sec
[meth_main] Data output time: 43.977 sec
[main] Version: 0.6
[main] CMD: ./f5c call-methylation -t 8 -x jetson-xavier -B 10000000 -r [FASTQ_PATH] -g [REF_GENOME_PATH] -b [BAM_PATH]
[main] Real time: 1360.456 sec; CPU time: 8689.180 sec; Peak RAM: 4.476 GB

PS. I did get some nice blue indication that GPU might be overloaded, so the whole thing might need some tweaking, but overall, that's the result. Thanks again!

**Comment by hasindu2008** [comment]
Thank you very much for the comments.

I think the second -O option comes from an environmental variable set on your system. Infact, `-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/magos/miniforge3/include` are not specified in the make file. Most probably your CPPFLAGS or CFLAGS is set to include those. Nevertheless, removing the -O in the make file manually is alright in your case.

The Xavier profile I have included is for the Xavier dev kit with 16 GB of memory. Your Xavier AGX may be having 32 GB of memory and if it is the case your choice of -B is appropriate.

**Comment by PhiloVa** [comment]
Yes indeed, it's the 32Gb version.

So far best results with -B 9000000 and -K 2048

Considering the low power of CPU's on the Xavier, passing more workload on the GPU might increase even more the overall efficiency.

Thanks!

**Comment by hasindu2008** [comment]
Can I know how many cores this particular jetson Xavier has?

**Comment by PhiloVa** [comment]
Sure, 
It's the Jetson AGX Xavier Dev Kit:

64bit 8-core CPU @ 2265MHz
512-core Volta GPU /w 64 tensor cores @ 1377MHz
