### ISSUE TITLE
Getting the contigs of interest from the reference sequence instead of the BAM file

### ISSUE THREAD

**Issue by andreaswallberg** [hasindu2008/f5c#84]
Dear @hasindu2008 

This is a feature request.

Having set up my fast5-indexes and BAM file, I have realized that I sometimes want to run the analyses across specific contigs (up to 20-30 thousand ones in my case), rather than the whole genome. 

I am aware that the program be specified to scan only a particular sequence, but there is an substantial overhead associated with running just across a short contig and then restart the program and run it again.

I guess one way to accomplish what I want is to filter the BAM file so that it only contains mappings against the contigs of interest.

Another, much simpler method is to filter the reference genome so that it only contains the contigs of interest. In my case, also in a specific order of interest, from the most prioritized sequences to the least. This is easy to accomplish by just updating the reference genome file.

However, it seems like the program defaults to scanning the data according to the order of contigs in the BAM file, not in the reference genome file.

Would it be possible to tweak the code so that the program gets the target contigs for analyses, and their order of analysis, from the reference file instead of the BAM file?

This would make the program very flexible and accommodate various ad-hoc subsets for analysis, if needed.

**Comment by hasindu2008** [comment]
@andreaswallberg 

Currently, f5c uses an hts iterator in htslib (_sam_itr_queryi_) that iterates through a given _chr:beg-end_ region.  When a batch of alignment records are loaded, the corresponding sequences are located from the reference genome through _faidx_. Doing vice versa is possible but require some code restructuring. An easier method that I can think of is using _sam_itr_regions_ in htslib that accepts a list of regions (have to look further into it to be sure).  What would be the best way to accept the list of the required regions - a bed file to the _-w_ option? 

I will try my best to get this feature onto the next _f5c_ release. Thank you for the suggestion.

**Comment by hasindu2008** [comment]
In the latest release of f5c, now you can provide a list of regions as a bed file (_-w regions.bed_).  Cloding this issue for now. Feel free to reopen this issue if you have any more thoughts. Suggestions are always appreciated :)
