### ISSUE TITLE
[Request] Set default --meth-out-version 2

### ISSUE THREAD

**Issue by jolespin** [hasindu2008/f5c#86]
This will make it much easier to use `pycoMeth` more seamlessly.  I found this out after I spent a few weeks processing all of my sample using most of our compute budget so I couldn't reprocess the samples. 

https://github.com/a-slide/pycoMeth/issues/49

**Comment by hasindu2008** [comment]
Thanks for this reminder. I would get this in the next release :D

**Comment by hasindu2008** [comment]
done in the latest release.
