### ISSUE TITLE
Short option for "window" missing in "call-methylation

### ISSUE THREAD

**Issue by kpalin** [hasindu2008/f5c#90]
Need to add 'w:' to 
 https://github.com/hasindu2008/f5c/blob/37ceb5a7f78eb8539536f06c7e00cea2483ca624/src/meth_main.c#L217

**Comment by hasindu2008** [comment]
Indeed, I have forgotten to add that it seems. Thank you for reporting this. Will be fixed in the next version :)

**Comment by hasindu2008** [comment]
Fixed in the latest version.
