### ISSUE TITLE
f5c eventaling -w flag behaviour

### ISSUE THREAD

**Issue by F0nz0** [hasindu2008/f5c#92]
Hi,
thank you very much for your f5c software! It's a very powerful tool.

I'm very interested in the use of the -w flag in order to limit processing to a genomic region specified as chr:start-end.
In this context, for istance, if I launch the following command (with 1-based coordinates):

```
f5c eventalign \
    --reads reads.fasta \
    --bam reads-ref.sorted.bam \
    --genome ref_sub.fa \
    --scale-events \
    --print-read-names \
    --samples \
    -w 'gi|545778205|gb|U00096.3|-523261-527541:43-80' \
    --t 4 > ../reads-ref_w_flag.eventalign 2> ../f5c_eventalign_w_flag.err
```

I expect to retrieve reads mapping on the interval 42-80 (0-based). In the end, if I load the resulting table on a Pandas.DataFrame and I run the df.describe() command I obtained the following result:

![image](https://user-images.githubusercontent.com/41163796/134928171-09ee4a48-51fc-4618-bffc-9c92defa3ee3.png)

Thus if I want to obtain the 42-80 range in the final dataframe I have to add 5 position to the end coordinate into the -w flag of f5c eventalign command. I tested also other positions and I found the same shift of 5 position on the end coordinate. 

Am I doing something wrong?

Thank you in advance!

**Comment by hasindu2008** [comment]
HI,

Thanks for using f5c.  f5c internally uses the `sam_itr_querys()` call in htslib to get the alignments that overlap a particular region. So as far as I am aware, the behaviour is similar to the alignments you get for `samtools view <REGION>`. 

Could you put a screenshot of your alignments on IGV or something for this particular region?
Or if this data is public and sharable I can have a look.

**Comment by F0nz0** [comment]
Hi and thank you for your immediate answer! 

The data is public and comes from the nanopolish github test dataset "ecoli_2kb_region".
Here I've had to substitute into the ref.fa file the ":" char to "-" in order to avoid problems in the downstream analysis. 
I'm sending here the compressed folder with data:

[ecoli_2kb_region.zip](https://github.com/hasindu2008/f5c/files/7241968/ecoli_2kb_region.zip)

This is instead the script that I used and I cited above:

 

```
> f5c eventalign \
>     --reads reads.fasta \
>     --bam reads-ref.sorted.bam \
>     --genome ref_sub.fa \
>     --scale-events \
>     --print-read-names \
>     --samples \
>     -w 'gi|545778205|gb|U00096.3|-523261-527541:43-80' \
>     --t 4 > ../reads-ref_w_flag.eventalign 2> ../f5c_eventalign_w_flag.err
```

**Comment by hasindu2008** [comment]
Ok right. It is because if the k-mer size of the model used being 6. 
If I run samtools faidx to grab the 43-81 (1- based) region:
`samtools faidx  ref_sub.fa  "gi|545778205|gb|U00096.3|-523261-527541:43-81"
>gi|545778205|gb|U00096.3|-523261-527541:43-81
TATGGCGGTCCCATTGTCCAGGGTTCGGCAGGTGTAAGA`

In the event alignment output, the first row is for k-mer which is at 42th (0-index) position  which is TATGGC	
gi|545778205|gb|U00096.3|-523261-527541	42	TATGGC	

The last row is for the k-mer GTAAGA which starts at 75th (0-index) position and end at 80th (0-index) option.
gi|545778205|gb|U00096.3|-523261-527541	75	GTAAGA

So any k-mer starting beyond that has bases after 80th position and that is why they are cut off.
Hope my explanation is clear.

**Comment by F0nz0** [comment]
Ok it's clear! Thank you very much for your clarification.
In the end, If I want to calculate the currents mapping from 42 to 80 of reference, I have to increase the end position until the last kmer has "incorporated" the 80th nucleotide, right?

**Comment by hasindu2008** [comment]
Yeh, that is the easiest way.

**Comment by F0nz0** [comment]
I'm very grateful to you for your precise answers! Thank you very much!
