### ISSUE TITLE
5fc index --sequencing_summary

### ISSUE THREAD

**Issue by will-NYGC** [hasindu2008/f5c#93]
Can you clarify the issues with the sequencing_summary option? It speeds things up enormously and so I hope to keep using it if possible. What exactly are the formatting issues and/or the proper format specifications for sequencing_summary.txt.

**Comment by hasindu2008** [comment]
Hi

sequencing_summary.txt is a file generated by ONT's MinKNOW and unfortunately, it does not have any specification (even it should have one!) and keeps changing frequently. So this option needs to be updated whenever ONT changes the sequencing summary format. Are you encountering any problems with it?

**Comment by will-NYGC** [comment]
We haven't had problems yet but just noticed the warning in the documentation. Will it error out if there's an issue? Or will the output be wrong? As long as it's causing easily detectable problems, I think it's worth it to us to keep using it.

**Comment by hasindu2008** [comment]
Yes, it will error out if there is an issue and will not affect the output. The sequencing summary file's use is to quickly determine which read ID maps to which fast5 file. If the corresponding column name in the sequencing summary changed, f5c will not be able to use the summary file and will anyway fall back to the default method.

**Comment by will-NYGC** [comment]
ok thanks, i think you can close this issue then.
On Oct 1, 2021, 8:48 PM -0400, Hasindu Gamaarachchi ***@***.***>, wrote:
> Yes, it will error out if there is an issue and will not affect the output. The sequencing summary file's use is to quickly determine which read ID maps to which fast5 file. If the corresponding column name in the sequencing summary changed, f5c will not be able to use the summary file and will anyway fall back to the default method.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

-- 

This message is for the recipient’s use only, and may contain 
confidential, privileged or protected information. Any unauthorized use or 
dissemination of this communication is prohibited. If you received this 
message in error, please immediately notify the sender and destroy all 
copies of this message. The recipient should check this email and any 
attachments for the presence of viruses, as we accept no liability for any 
damage caused by any virus transmitted by this email.

**Comment by hasindu2008** [comment]
No problem. Feel free to reopen or open a new issue if you have any more questions in the future.
