### ISSUE TITLE
blow5 file as input file

### ISSUE THREAD

**Issue by mantonglaw** [hasindu2008/f5c#97]
Could I use compressed blow5 as input file for f5c?
Thanks in advance!

**Comment by hasindu2008** [comment]
Yes. The master branch supports compressed BLOW5.  Could you please compile from it?
The release version and binaries is a bit old and do not support compression. I should make a new release soon.

**Comment by mantonglaw** [comment]
Thanks， I am looking forward the newest verison.
I have another puzzle:
I installed f5c(v 0.7)  from conda, I run f5c index, and the following wrong happened,

"[slow5_hdr_init::ERROR] File version '0.2.0' is higher than the max slow5 version '0.1.0' supported by this slow5lib! Please use a newer version of slow5lib. At src/slow5.c:473
[slow5_init::ERROR] Parsing slow5 header of file '/share3/lius/raw/DNA/batch2/H1174_T3A/merge_file.slow5' failed. At src/slow5.c:121
[index_main::ERROR] Error in opening slowfile /share3/lius/raw/DNA/batch2/H1174_T3A/merge_file.slow5"


Could you give me some suggestions? 
Thanks a lot.

**Comment by hasindu2008** [comment]
Yeh. The version on conda is also a bit outdated and does not support compressed BLOW5. I will create a new release tomorrow and this will solve the issue.

**Comment by mantonglaw** [comment]
Thank you so much！
I can't wait to try your tool to accelerate our methylation calling. I will try it asap!

**Comment by hasindu2008** [comment]
Hi,
I have released a new version _f5c_. It might take a few days for the _conda_ version to appear on the repository. 
Meanwhile, you can download the binaries from https://github.com/hasindu2008/f5c/releases/download/v0.8/f5c-v0.8-binaries.tar.gz extract and run. The binaries should work on most of Linux systems.

**Comment by hasindu2008** [comment]
f5c 0.8 is now available on a conda. Give it a go and let me know if you encounter any difficulties or issues.

**Comment by mantonglaw** [comment]
Hi @hasindu2008,
Thanks for your upgrate!
I already tested f5c 0.8 yesterday. I had yet encountered any problems. I will countinue to use it, I will report as soon as possible if I find any Issues  or difficulties!
Thanks again!
